{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"remove","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BlackList","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"screen","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"screen name to remove fro the invalid screens list","type":"text"}],"type":"paragraph"}],"name":"screen"}]},{"content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Note: If no screens are in the black list the system will ignore its limitations"}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/joynedmobilesdk\/joynedsdk\/remove(blacklist:)"]},{"paths":["\/documentation\/joynedmobilesdk\/joynedsdk\/remove(blacklist:)"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"generated":true,"title":"SDK Screen Validation","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/append(WhiteList:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/remove(WhiteList:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/append(BlackList:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/clearScreensBlackList()","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/_01_screen-llst"]}],"sections":[],"metadata":{"externalID":"c:@M@JoynedMobileSDK@objc(cs)JoynedSDK(cm)removeWithBlackList:","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"remove","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"BlackList"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"role":"symbol","symbolKind":"method","modules":[{"name":"JoynedMobileSDK"}],"roleHeading":"Type Method","title":"remove(BlackList:)","navigatorTitle":[{"kind":"identifier","text":"removeWithBlackList:"}]},"identifier":{"url":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/remove(BlackList:)","interfaceLanguage":"swift"},"abstract":[{"text":"Use this method to remove a  screen name to the system black list","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"On screens which appear in the blacklist the Joyned mobile SDK will not present it’s floating content,"}],"hierarchy":{"paths":[["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK"],["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK"]]},"references":{"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK/clearScreensBlackList()":{"title":"clearScreensBlackList()","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Use this method to clear the invalid screen names from the system black list"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdk\/clearscreensblacklist()","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/clearScreensBlackList()","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clearScreensBlackList"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"clearScreensBlackList"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK":{"title":"JoynedMobileSDK","abstract":[{"text":"We help people book together. With a better booking experience, better business results","type":"text"}],"type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","role":"collection","url":"\/documentation\/joynedmobilesdk","kind":"symbol"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK/remove(WhiteList:)":{"title":"remove(WhiteList:)","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Use this method to remove a screen name to the system white list"},{"text":" ","type":"text"},{"text":"On screens which appear in the whitelist the Joyned mobile SDK will present it’s floating content,","type":"text"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdk\/remove(whitelist:)","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/remove(WhiteList:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"remove"},{"text":"(","kind":"text"},{"text":"WhiteList","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"removeWithWhiteList:"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK/remove(BlackList:)":{"title":"remove(BlackList:)","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedsdk\/remove(blacklist:)","abstract":[{"type":"text","text":"Use this method to remove a  screen name to the system black list"},{"text":" ","type":"text"},{"text":"On screens which appear in the blacklist the Joyned mobile SDK will not present it’s floating content,","type":"text"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/remove(BlackList:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"remove"},{"text":"(","kind":"text"},{"text":"BlackList","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"removeWithBlackList:"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/_01_screen-llst":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/_01_screen-llst","title":"Screen Validation Controls","url":"\/documentation\/joynedmobilesdk\/_01_screen-llst","kind":"article","abstract":[{"type":"text","text":"Joyned Mobile SDK screen change monitor"}],"type":"topic","role":"article"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK/append(BlackList:)":{"title":"append(BlackList:)","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedsdk\/append(blacklist:)","abstract":[{"type":"text","text":"Use this method to add a new screen name to the system black list"},{"text":" ","type":"text"},{"text":"On screens which appear in the blacklist the Joyned mobile SDK will not present it’s floating content,","type":"text"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/append(BlackList:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"append"},{"text":"(","kind":"text"},{"text":"BlackList","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"appendWithBlackList:"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK":{"title":"JoynedSDK","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The main public access class to ther Joyned mobile SDK, use it to interact with the system"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdk","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JoynedSDK"}],"navigatorTitle":[{"text":"JoynedSDK","kind":"identifier"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/GettingStarted":{"title":"Getting Started with Joyned mobile SDK","abstract":[],"type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","role":"collectionGroup","url":"\/documentation\/joynedmobilesdk\/gettingstarted","kind":"article"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK/append(WhiteList:)":{"title":"append(WhiteList:)","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedsdk\/append(whitelist:)","abstract":[{"type":"text","text":"Use this method to add a new screen name to the system white list"},{"text":" ","type":"text"},{"text":"On screens which appear in the whitelist the Joyned mobile SDK will present it’s floating content,","type":"text"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/append(WhiteList:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"append"},{"text":"(","kind":"text"},{"text":"WhiteList","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"appendWithWhiteList:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"removeWithBlackList:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"removeWithBlackList:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":[{"title":"SDK Screen Validation","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/append(WhiteList:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/remove(WhiteList:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/append(BlackList:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/clearScreensBlackList()","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/_01_screen-llst"],"generated":true}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"removeWithBlackList:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"screen"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"clearScreensBlackList","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1clearScreensBlackList()\/title"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1clearScreensBlackList()\/fragments","value":[{"kind":"text","text":"+ "},{"text":"clearScreensBlackList","kind":"identifier"}]},{"value":"removeWithWhiteList:","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1remove(WhiteList:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"removeWithWhiteList:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1remove(WhiteList:)\/fragments"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1remove(BlackList:)\/title","value":"removeWithBlackList:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1remove(BlackList:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"removeWithBlackList:"}]},{"value":"appendWithBlackList:","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1append(BlackList:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"appendWithBlackList:"}],"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1append(BlackList:)\/fragments"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK\/title","value":"JoynedSDK","op":"replace"},{"value":[{"kind":"identifier","text":"JoynedSDK"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK\/fragments","op":"replace"},{"op":"replace","value":"appendWithWhiteList:","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1append(WhiteList:)\/title"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1append(WhiteList:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"appendWithWhiteList:"}],"op":"replace"}]}]}