{"metadata":{"roleHeading":"Article","title":"Library installation","role":"article","modules":[{"name":"JoynedMobileSDK"}]},"seeAlsoSections":[{"generated":true,"title":"Essentials","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSample","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/joynedmobilesdk\/_00_installation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/joynedmobilesdk\/_00_installation"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"How to install this library"}],"primaryContentSections":[{"kind":"content","content":[{"anchor":"overview","level":2,"text":"Overview","type":"heading"},{"tabs":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"identifier":"https:\/\/swift.org\/package-manager\/","isActive":true,"type":"reference"},{"type":"text","text":" is a tool for automating the distribution of Swift code and is integrated into the "},{"code":"swift","type":"codeVoice"},{"type":"text","text":" compiler."}]},{"inlineContent":[{"text":"Once you have your Swift package set up, adding JoynedMobileSDK as a dependency is as easy as adding it to the ","type":"text"},{"type":"codeVoice","code":"dependencies"},{"type":"text","text":" value of your "},{"code":"Package.swift","type":"codeVoice"},{"type":"text","text":" or the Package list in Xcode."}],"type":"paragraph"},{"syntax":"swift","code":["dependencies: [","    .package(url: \"https:\/\/github.com\/gamitee-dev\/ios-sdk-storage.git\", .upToNextMajor(from: \"1.0.0\"))","]"],"type":"codeListing"},{"inlineContent":[{"type":"text","text":"Normally you’ll want to depend on the "},{"type":"codeVoice","code":"Joyned"},{"type":"text","text":" target:"}],"type":"paragraph"},{"type":"codeListing","code":[".product(name: \"JoynedMobileSDK\", package: \"JoynedMobileSDK\")"],"syntax":"swift"}],"title":"Swift package manager"},{"content":[{"inlineContent":[{"identifier":"https:\/\/cocoapods.org","type":"reference","isActive":true},{"type":"text","text":" is a dependency manager for Cocoa projects."}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"To install cocoapods via gem if needed"}]},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"text":"Open terminal","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Type "},{"type":"codeVoice","code":"$ [sudo] gem install cocoapods"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Press enter"}],"type":"paragraph"}]}]}]}],"type":"unorderedList"},{"type":"paragraph","inlineContent":[{"text":"For more usage and installation instructions, visit their website.","type":"text"}]},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"To integrate Joyned into your Xcode project using CocoaPods, specify it in your "},{"type":"codeVoice","code":"Podfile"},{"type":"text","text":":"}],"type":"paragraph"}]}],"type":"unorderedList"},{"code":["target ‘YOUR_PROJECT’ do","    …","    pod 'JoynedMobileSDK' , '~> 1.0.0'","end"],"syntax":"ruby","type":"codeListing"},{"items":[{"content":[{"inlineContent":[{"text":"In the terminal run ","type":"text"},{"type":"codeVoice","code":"pod install"}],"type":"paragraph"},{"type":"heading","text":"Note for Mac M1 users:","level":4,"anchor":"Note-for-Mac-M1-users"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Mac M1 architecture is not directly compatible with Cocoapods. If you encounter issues when installing pods, you can solve it by running:"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"sudo arch -x86_64 gem install ffi"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"arch -x86_64 pod install"},{"text":" ","type":"text"},{"type":"text","text":"These commands install the ffi package, to load dynamically-linked libraries and let you run the pod install properly, and runs pod install with the proper architecture."}]}]}],"type":"unorderedList"}]}],"type":"unorderedList"}],"title":"Cocoa-pods"},{"title":"Manually","content":[{"type":"paragraph","inlineContent":[{"text":"If you prefer not to use any of the other dependency managers, you can integrate Joyned into your project manually by adding the XCFramework to the project.","type":"text"}]}]}],"type":"tabNavigator"}]}],"identifier":{"url":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/_00_installation","interfaceLanguage":"swift"},"sections":[],"kind":"article","hierarchy":{"paths":[["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK"],["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted"]]},"references":{"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK":{"title":"JoynedMobileSDK","abstract":[{"text":"We help people book together. With a better booking experience, better business results","type":"text"}],"type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","role":"collection","url":"\/documentation\/joynedmobilesdk","kind":"symbol"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK":{"title":"JoynedSDK","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The main public access class to ther Joyned mobile SDK, use it to interact with the system"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdk","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JoynedSDK"}],"navigatorTitle":[{"text":"JoynedSDK","kind":"identifier"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/GettingStarted":{"title":"Getting Started with Joyned mobile SDK","abstract":[],"type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","role":"collectionGroup","url":"\/documentation\/joynedmobilesdk\/gettingstarted","kind":"article"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSample":{"role":"sampleCode","url":"\/documentation\/joynedmobilesdk\/joynedsample","title":"Sample code - Voyage App","kind":"article","abstract":[{"type":"text","text":"Integrate JoynedMobileSDK into an iOS app for booking and ordering togather."}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSample","type":"topic"},"https://cocoapods.org":{"type":"link","identifier":"https:\/\/cocoapods.org","url":"https:\/\/cocoapods.org","title":"CocoaPods","titleInlineContent":[{"text":"CocoaPods","type":"text"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDKDelegate":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"JoynedSDKDelegate"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate","abstract":[{"type":"text","text":"The Joyned mobile SDK main delegation protocol, implement this to recive notifications on major actions taken by the SDK and affect its behavior"}],"title":"JoynedSDKDelegate","url":"\/documentation\/joynedmobilesdk\/joynedsdkdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"JoynedSDKDelegate","kind":"identifier"}]},"https://swift.org/package-manager/":{"identifier":"https:\/\/swift.org\/package-manager\/","title":"Swift Package Manager","url":"https:\/\/swift.org\/package-manager\/","type":"link","titleInlineContent":[{"text":"Swift Package Manager","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"replace","value":[{"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSample","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate"],"title":"Essentials","generated":true}]},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK\/title","value":"JoynedSDK"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK\/fragments","value":[{"kind":"identifier","text":"JoynedSDK"}]},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDKDelegate\/title","value":"JoynedSDKDelegate"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDKDelegate\/fragments","value":[{"kind":"identifier","text":"JoynedSDKDelegate"}]}]}]}