{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate\/joynedButton(_:productOfferingForItem:)"},"hierarchy":{"paths":[["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate"],["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate"],["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate"],["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate"]]},"sections":[],"abstract":[{"text":"Called when the User clicks the button, if the button is contained within a ","type":"text"},{"type":"codeVoice","code":"UICollectionView"},{"text":" and is visiable on screen","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Asks for the relevent product offering, provides the index path associated with the button"}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"joynedButton"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@JoynedMobileSDK@objc(cs)JoynedButton","text":"JoynedButton","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"productOfferingForItem"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@JoynedMobileSDK@objc(cs)JoynedOfferingRequest","text":"JoynedOfferingRequest","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"joynedButton(_:productOfferingForItem:)","symbolKind":"method","role":"symbol","navigatorTitle":[{"text":"joynedButton:productOfferingForItem:","kind":"identifier"}],"externalID":"c:@M@JoynedMobileSDK@objc(pl)JoynedButtonDelegate(im)joynedButton:productOfferingForItem:","roleHeading":"Instance Method","modules":[{"name":"JoynedMobileSDK"}]},"seeAlsoSections":[{"title":"Offering computations","generated":true,"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate\/joynedButton(_:productOfferingFor:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate\/joynedButton(_:productOfferingForRaw:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"joynedButton","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"button","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"JoynedButton","kind":"typeIdentifier","preciseIdentifier":"c:@M@JoynedMobileSDK@objc(cs)JoynedButton","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton"},{"kind":"text","text":", "},{"text":"productOfferingForItem","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"indexPath","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"JoynedOfferingRequest","preciseIdentifier":"c:@M@JoynedMobileSDK@objc(cs)JoynedOfferingRequest","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingRequest"},{"kind":"text","text":"?"}],"languages":["swift"]}]},{"content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Note: Only one method will be called out of the TableView\/CollectionView\/Location related methods"}]}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/joynedmobilesdk\/joynedbuttondelegate\/joynedbutton(_:productofferingforitem:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/joynedmobilesdk\/joynedbuttondelegate\/joynedbutton(_:productofferingforitem:)"]}],"kind":"symbol","references":{"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButtonDelegate/joynedButton(_:productOfferingFor:)":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate\/joynedButton(_:productOfferingFor:)","kind":"symbol","type":"topic","title":"joynedButton(_:productOfferingFor:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"joynedButton"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"JoynedButton","preciseIdentifier":"c:@M@JoynedMobileSDK@objc(cs)JoynedButton"},{"text":", ","kind":"text"},{"text":"productOfferingFor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"},{"kind":"text","text":") -> "},{"text":"JoynedOfferingRequest","kind":"typeIdentifier","preciseIdentifier":"c:@M@JoynedMobileSDK@objc(cs)JoynedOfferingRequest"},{"kind":"text","text":"?"}],"required":true,"abstract":[{"text":"Called when the User clicks the button,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Asks for the relevent product offering, provides the touch location associated with the button, in the window coordinatespace"}],"role":"symbol","navigatorTitle":[{"text":"joynedButton:productOfferingFor:","kind":"identifier"}],"url":"\/documentation\/joynedmobilesdk\/joynedbuttondelegate\/joynedbutton(_:productofferingfor:)"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/GettingStarted":{"title":"Getting Started with Joyned mobile SDK","abstract":[],"type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","role":"collectionGroup","url":"\/documentation\/joynedmobilesdk\/gettingstarted","kind":"article"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButtonDelegate/joynedButton(_:productOfferingForRaw:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"joynedButton"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@JoynedMobileSDK@objc(cs)JoynedButton","text":"JoynedButton","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"productOfferingForRaw"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier","text":"IndexPath"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@JoynedMobileSDK@objc(cs)JoynedOfferingRequest","text":"JoynedOfferingRequest","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"Called when the User clicks the button, if the button is contained within a "},{"code":"UITableView","type":"codeVoice"},{"text":" and is visiable on screen","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Asks for the relevent product offering, provides the index path associated with the button"}],"title":"joynedButton(_:productOfferingForRaw:)","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate\/joynedButton(_:productOfferingForRaw:)","kind":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedbuttondelegate\/joynedbutton(_:productofferingforraw:)","required":true,"role":"symbol","navigatorTitle":[{"text":"joynedButton:productOfferingForRaw:","kind":"identifier"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK":{"title":"JoynedMobileSDK","abstract":[{"text":"We help people book together. With a better booking experience, better business results","type":"text"}],"type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","role":"collection","url":"\/documentation\/joynedmobilesdk","kind":"symbol"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton":{"title":"JoynedButton","abstract":[{"type":"text","text":"A Joyned UI element meant for usage in the host application, acts as a card like display element, supports border, shadow, corner cliping & more"}],"type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton","role":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedbutton","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"JoynedButton","kind":"identifier"}],"navigatorTitle":[{"text":"JoynedButton","kind":"identifier"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedOfferingRequest":{"type":"topic","kind":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedofferingrequest","title":"JoynedOfferingRequest","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingRequest","abstract":[{"text":"A data object containing the offering information to be reported to the Joyned servers","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"JoynedOfferingRequest","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JoynedOfferingRequest"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButtonDelegate/joynedButton(_:productOfferingForItem:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"joynedButton","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@JoynedMobileSDK@objc(cs)JoynedButton","kind":"typeIdentifier","text":"JoynedButton"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"productOfferingForItem"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"JoynedOfferingRequest","kind":"typeIdentifier","preciseIdentifier":"c:@M@JoynedMobileSDK@objc(cs)JoynedOfferingRequest"},{"text":"?","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"Called when the User clicks the button, if the button is contained within a "},{"type":"codeVoice","code":"UICollectionView"},{"type":"text","text":" and is visiable on screen"},{"text":" ","type":"text"},{"text":"Asks for the relevent product offering, provides the index path associated with the button","type":"text"}],"title":"joynedButton(_:productOfferingForItem:)","kind":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate\/joynedButton(_:productOfferingForItem:)","url":"\/documentation\/joynedmobilesdk\/joynedbuttondelegate\/joynedbutton(_:productofferingforitem:)","navigatorTitle":[{"kind":"identifier","text":"joynedButton:productOfferingForItem:"}],"role":"symbol"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButtonDelegate":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate","navigatorTitle":[{"kind":"identifier","text":"JoynedButtonDelegate"}],"title":"JoynedButtonDelegate","url":"\/documentation\/joynedmobilesdk\/joynedbuttondelegate","abstract":[{"type":"text","text":"Methods for managing JoynedButton behavior, allows the system a way to pass navigation requests & more"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"JoynedButtonDelegate"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"joynedButton:productOfferingForItem:","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"joynedButton:productOfferingForItem:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":[{"title":"Offering computations","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate\/joynedButton(_:productOfferingFor:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate\/joynedButton(_:productOfferingForRaw:)"],"generated":true}],"op":"replace"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"JoynedOfferingRequest","preciseIdentifier":"c:@M@JoynedMobileSDK@objc(cs)JoynedOfferingRequest","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingRequest"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"joynedButton:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton","text":"JoynedButton","preciseIdentifier":"c:@M@JoynedMobileSDK@objc(cs)JoynedButton","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"button"},{"kind":"text","text":" "},{"text":"productOfferingForItem:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSIndexPath","preciseIdentifier":"c:objc(cs)NSIndexPath","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"indexPath","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButtonDelegate~1joynedButton(_:productOfferingFor:)\/title","op":"replace","value":"joynedButton:productOfferingFor:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"joynedButton:productOfferingFor:","kind":"identifier"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButtonDelegate~1joynedButton(_:productOfferingFor:)\/fragments"},{"value":"joynedButton:productOfferingForRaw:","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButtonDelegate~1joynedButton(_:productOfferingForRaw:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"joynedButton:productOfferingForRaw:","kind":"identifier"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButtonDelegate~1joynedButton(_:productOfferingForRaw:)\/fragments"},{"value":"JoynedButton","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton\/title"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton\/fragments","value":[{"kind":"identifier","text":"JoynedButton"}],"op":"replace"},{"op":"replace","value":"JoynedOfferingRequest","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingRequest\/title"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingRequest\/fragments","op":"replace","value":[{"kind":"identifier","text":"JoynedOfferingRequest"}]},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButtonDelegate~1joynedButton(_:productOfferingForItem:)\/title","value":"joynedButton:productOfferingForItem:"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButtonDelegate~1joynedButton(_:productOfferingForItem:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"joynedButton:productOfferingForItem:"}]},{"value":"JoynedButtonDelegate","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButtonDelegate\/title"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButtonDelegate\/fragments","value":[{"text":"JoynedButtonDelegate","kind":"identifier"}],"op":"replace"}]}]}