{"hierarchy":{"paths":[["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK"],["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted"],["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK"],["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK"]]},"identifier":{"url":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/_02_hosted-ui","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/joynedmobilesdk\/_02_hosted-ui"]},{"paths":["\/documentation\/joynedmobilesdk\/_02_hosted-ui"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"seeAlsoSections":[{"generated":true,"title":"Hosted Joyned UI","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate"]}],"abstract":[{"type":"text","text":"Hosted Joyned UI"},{"type":"text","text":" "},{"text":"Joyned mobile SDK provides a few views which are ment to be used within application that hosts the SDK","type":"text"}],"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","text":"Overview","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"There are two ways to integrated Joyned mobile SDK views into the host application:"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"via Xib\/Storyboard","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"via Code","type":"text"}],"type":"paragraph"}]}]},{"text":"Xib\/Storyboard","type":"heading","anchor":"XibStoryboard","level":3},{"inlineContent":[{"text":"To integrate a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton"},{"text":" in to Xib or Storyboard based UI all you need to do is to add a view element to the Xib\/Storyboard document and set its custom class to ","type":"text"},{"isActive":true,"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton","type":"reference"},{"type":"text","text":"."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"Make sure to also set the ","type":"text"},{"type":"codeVoice","code":"module"},{"text":" value in the inspector to ","type":"text"},{"type":"codeVoice","code":"JoynedMobileSDK"}]},{"inlineContent":[{"identifier":"screenshot_joyned_button.png","type":"image"}],"type":"paragraph"},{"text":"Code Integration","type":"heading","anchor":"Code-Integration","level":3},{"inlineContent":[{"text":"To integrate a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton"},{"type":"text","text":" in to a UIKit code based UI, use the following code:"}],"type":"paragraph"},{"syntax":"swift","type":"codeListing","code":["lass ExampleViewController : UIViewController","{","    \/\/ MARK: - type - enum","    ","    \/\/ MARK: - Properties","    internal var venue : Venue!","","    \/\/ MARK: - View LifeCycle","    override func viewDidLoad()","    {","        super.viewDidLoad()","","","        let button = JoynedSDK.generateJoynedButton(frame: CGRect(x: 100, y: 500, width: 70, height: 34), with: self)","        view.addSubview(button)","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"text":"Also see","type":"text"}]},{"type":"text","text":":"}]},{"type":"links","style":"list","items":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/generateJoynedButton(frame:with:)"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Make sure that you implement the button’s delegate protocol and set it’s delegate like so:"}]},{"type":"codeListing","code":["extension ExampleViewController : JoynedButtonDelegate","{","    func willPresentMobileSDKContent()","    {","        logger.debug()","    }","    ","    func joynedButton(_ button: JoynedButton, productOfferingFor location: CGPoint) -> JoynedNavigationRequestProtocol?","    {","        logger.debug()","        ","        return encode(product: venue)","    }","    ","    private func encode(product item: Venue?) -> JoynedNavigationRequestProtocol?","    {","        guard let venue   = item              else { return nil }","        guard let product = venue.toPayload() else { return nil }","        guard let extra   = venue.toJSON()    else { return nil }","        return JoynedNavigationRequest(offeringString: product, extraString: extra)","    }","}"],"syntax":"swift"},{"type":"heading","text":"For more information see:","anchor":"For-more-information-see","level":4},{"type":"links","style":"list","items":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate"]}]}],"metadata":{"roleHeading":"Article","role":"article","modules":[{"name":"JoynedMobileSDK"}],"title":"Hosted UI"},"references":{"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK/generateJoynedButton(frame:with:)":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/generateJoynedButton(frame:with:)","navigatorTitle":[{"text":"generateJoynedButtonWithFrame:with:","kind":"identifier"}],"title":"generateJoynedButton(frame:with:)","url":"\/documentation\/joynedmobilesdk\/joynedsdk\/generatejoynedbutton(frame:with:)","abstract":[{"type":"text","text":"Use this method to generate a new instance of "},{"type":"reference","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton","isActive":true}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"generateJoynedButton","kind":"identifier"},{"text":"(","kind":"text"},{"text":"frame","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"text":"JoynedButtonDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@JoynedMobileSDK@objc(pl)JoynedButtonDelegate"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:@M@JoynedMobileSDK@objc(cs)JoynedButton","text":"JoynedButton","kind":"typeIdentifier"}],"type":"topic"},"screenshot_joyned_button.png":{"type":"image","alt":"Joyned button example","identifier":"screenshot_joyned_button.png","variants":[{"traits":["1x","light"],"url":"\/images\/screenshot_joyned_button.png"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK":{"title":"JoynedMobileSDK","abstract":[{"text":"We help people book together. With a better booking experience, better business results","type":"text"}],"type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","role":"collection","url":"\/documentation\/joynedmobilesdk","kind":"symbol"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK":{"title":"JoynedSDK","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The main public access class to ther Joyned mobile SDK, use it to interact with the system"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdk","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JoynedSDK"}],"navigatorTitle":[{"text":"JoynedSDK","kind":"identifier"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton":{"title":"JoynedButton","abstract":[{"type":"text","text":"A Joyned UI element meant for usage in the host application, acts as a card like display element, supports border, shadow, corner cliping & more"}],"type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton","role":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedbutton","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"JoynedButton","kind":"identifier"}],"navigatorTitle":[{"text":"JoynedButton","kind":"identifier"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/GettingStarted":{"title":"Getting Started with Joyned mobile SDK","abstract":[],"type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","role":"collectionGroup","url":"\/documentation\/joynedmobilesdk\/gettingstarted","kind":"article"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButtonDelegate":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate","navigatorTitle":[{"kind":"identifier","text":"JoynedButtonDelegate"}],"title":"JoynedButtonDelegate","url":"\/documentation\/joynedmobilesdk\/joynedbuttondelegate","abstract":[{"type":"text","text":"Methods for managing JoynedButton behavior, allows the system a way to pass navigation requests & more"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"JoynedButtonDelegate"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate"],"title":"Hosted Joyned UI","generated":true}]},{"op":"replace","value":"generateJoynedButtonWithFrame:with:","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1generateJoynedButton(frame:with:)\/title"},{"value":[{"kind":"text","text":"+ "},{"text":"generateJoynedButtonWithFrame:with:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1generateJoynedButton(frame:with:)\/fragments"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK\/title","value":"JoynedSDK","op":"replace"},{"value":[{"text":"JoynedSDK","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK\/fragments"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton\/title","value":"JoynedButton","op":"replace"},{"op":"replace","value":[{"text":"JoynedButton","kind":"identifier"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton\/fragments"},{"value":"JoynedButtonDelegate","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButtonDelegate\/title"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButtonDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"JoynedButtonDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}