{"metadata":{"role":"symbol","modules":[{"name":"JoynedMobileSDK"}],"externalID":"c:JoynedMobileSDK.h@F@j_throw_objc","roleHeading":"Function","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"j_throw_objc"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSException","text":"NSException"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"j_throw_objc","kind":"identifier"}],"symbolKind":"func","title":"j_throw_objc(_:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/joynedmobilesdk\/j_throw_objc(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/joynedmobilesdk\/j_throw_objc(_:)"]}],"abstract":[{"type":"text","text":"Throws an Objective-C exception"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"j_throw_objc","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"exception","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSException","kind":"typeIdentifier","text":"NSException"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"NSException object to throw","type":"text"}],"type":"paragraph"}],"name":"exception"}]}],"hierarchy":{"paths":[["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK"],["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted"]]},"seeAlsoSections":[{"title":"Objective-C Utilities","generated":true,"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/j_try_objc(_:_:_:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/j_throw_objc(_:)"},"references":{"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/GettingStarted":{"title":"Getting Started with Joyned mobile SDK","abstract":[],"type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","role":"collectionGroup","url":"\/documentation\/joynedmobilesdk\/gettingstarted","kind":"article"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/j_try_objc(_:_:_:)":{"type":"topic","role":"symbol","title":"j_try_objc(_:_:_:)","abstract":[{"text":"Execute Swift code that could generate an Objective-C exception in here to catch and handle it gracefully (ie don’t crash)","type":"text"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"j_try_objc","kind":"identifier"},{"text":"(() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":", ("},{"text":"NSException","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSException"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":", () -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/joynedmobilesdk\/j_try_objc(_:_:_:)","navigatorTitle":[{"kind":"identifier","text":"j_try_objc"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/j_try_objc(_:_:_:)"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK":{"title":"JoynedMobileSDK","abstract":[{"text":"We help people book together. With a better booking experience, better business results","type":"text"}],"type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","role":"collection","url":"\/documentation\/joynedmobilesdk","kind":"symbol"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/j_throw_objc(_:)":{"type":"topic","role":"symbol","title":"j_throw_objc(_:)","abstract":[{"text":"Throws an Objective-C exception","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"j_throw_objc","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSException","text":"NSException","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/joynedmobilesdk\/j_throw_objc(_:)","navigatorTitle":[{"text":"j_throw_objc","kind":"identifier"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/j_throw_objc(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Function"},{"path":"\/metadata\/title","op":"replace","value":"j_throw_objc"},{"value":"func","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"j_throw_objc","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":[{"title":"Objective-C Utilities","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/j_try_objc(_:_:_:)"],"generated":true}],"op":"replace","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"j_throw_objc","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSException","preciseIdentifier":"c:objc(cs)NSException"},{"kind":"text","text":" * "},{"kind":"internalParam","text":"exception"},{"text":");","kind":"text"}]}],"kind":"declarations"}},{"value":"j_try_objc","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1j_try_objc(_:_:_:)\/title","op":"replace"},{"op":"replace","value":[{"text":"j_try_objc","kind":"identifier"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1j_try_objc(_:_:_:)\/fragments"},{"op":"replace","value":"j_throw_objc","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1j_throw_objc(_:)\/title"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1j_throw_objc(_:)\/fragments","op":"replace","value":[{"text":"j_throw_objc","kind":"identifier"}]}]}]}