{"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/joynedmobilesdk\/joynedbuttondelegate\/joynedbutton(_:productofferingfor:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/joynedmobilesdk\/joynedbuttondelegate\/joynedbutton(_:productofferingfor:)"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"joynedButton"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"button","kind":"internalParam"},{"kind":"text","text":": "},{"text":"JoynedButton","kind":"typeIdentifier","preciseIdentifier":"c:@M@JoynedMobileSDK@objc(cs)JoynedButton","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton"},{"kind":"text","text":", "},{"text":"productOfferingFor","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"location"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingRequest","preciseIdentifier":"c:@M@JoynedMobileSDK@objc(cs)JoynedOfferingRequest","text":"JoynedOfferingRequest"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Note: Only one method will be called out of the TableView\/CollectionView\/Location related methods"}]}],"kind":"content"}],"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate\/joynedButton(_:productOfferingForRaw:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate\/joynedButton(_:productOfferingForItem:)"],"title":"Offering computations"}],"identifier":{"url":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate\/joynedButton(_:productOfferingFor:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate"],["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate"],["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate"],["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate"]]},"abstract":[{"text":"Called when the User clicks the button,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Asks for the relevent product offering, provides the touch location associated with the button, in the window coordinatespace"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"JoynedMobileSDK"}],"roleHeading":"Instance Method","symbolKind":"method","title":"joynedButton(_:productOfferingFor:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"joynedButton"},{"text":"(","kind":"text"},{"text":"JoynedButton","kind":"typeIdentifier","preciseIdentifier":"c:@M@JoynedMobileSDK@objc(cs)JoynedButton"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"productOfferingFor"},{"kind":"text","text":": "},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JoynedMobileSDK@objc(cs)JoynedOfferingRequest","text":"JoynedOfferingRequest"},{"kind":"text","text":"?"}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"joynedButton:productOfferingFor:"}],"externalID":"c:@M@JoynedMobileSDK@objc(pl)JoynedButtonDelegate(im)joynedButton:productOfferingFor:","role":"symbol"},"references":{"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButtonDelegate":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate","navigatorTitle":[{"kind":"identifier","text":"JoynedButtonDelegate"}],"title":"JoynedButtonDelegate","url":"\/documentation\/joynedmobilesdk\/joynedbuttondelegate","abstract":[{"type":"text","text":"Methods for managing JoynedButton behavior, allows the system a way to pass navigation requests & more"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"JoynedButtonDelegate"}],"type":"topic"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton":{"title":"JoynedButton","abstract":[{"type":"text","text":"A Joyned UI element meant for usage in the host application, acts as a card like display element, supports border, shadow, corner cliping & more"}],"type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton","role":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedbutton","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"JoynedButton","kind":"identifier"}],"navigatorTitle":[{"text":"JoynedButton","kind":"identifier"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK":{"title":"JoynedMobileSDK","abstract":[{"text":"We help people book together. With a better booking experience, better business results","type":"text"}],"type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","role":"collection","url":"\/documentation\/joynedmobilesdk","kind":"symbol"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedOfferingRequest":{"type":"topic","kind":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedofferingrequest","title":"JoynedOfferingRequest","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingRequest","abstract":[{"text":"A data object containing the offering information to be reported to the Joyned servers","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"JoynedOfferingRequest","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JoynedOfferingRequest"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/GettingStarted":{"title":"Getting Started with Joyned mobile SDK","abstract":[],"type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","role":"collectionGroup","url":"\/documentation\/joynedmobilesdk\/gettingstarted","kind":"article"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButtonDelegate/joynedButton(_:productOfferingFor:)":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate\/joynedButton(_:productOfferingFor:)","kind":"symbol","type":"topic","title":"joynedButton(_:productOfferingFor:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"joynedButton"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"JoynedButton","preciseIdentifier":"c:@M@JoynedMobileSDK@objc(cs)JoynedButton"},{"text":", ","kind":"text"},{"text":"productOfferingFor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"},{"kind":"text","text":") -> "},{"text":"JoynedOfferingRequest","kind":"typeIdentifier","preciseIdentifier":"c:@M@JoynedMobileSDK@objc(cs)JoynedOfferingRequest"},{"kind":"text","text":"?"}],"required":true,"abstract":[{"text":"Called when the User clicks the button,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Asks for the relevent product offering, provides the touch location associated with the button, in the window coordinatespace"}],"role":"symbol","navigatorTitle":[{"text":"joynedButton:productOfferingFor:","kind":"identifier"}],"url":"\/documentation\/joynedmobilesdk\/joynedbuttondelegate\/joynedbutton(_:productofferingfor:)"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButtonDelegate/joynedButton(_:productOfferingForRaw:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"joynedButton"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@JoynedMobileSDK@objc(cs)JoynedButton","text":"JoynedButton","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"productOfferingForRaw"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier","text":"IndexPath"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@JoynedMobileSDK@objc(cs)JoynedOfferingRequest","text":"JoynedOfferingRequest","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"Called when the User clicks the button, if the button is contained within a "},{"code":"UITableView","type":"codeVoice"},{"text":" and is visiable on screen","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Asks for the relevent product offering, provides the index path associated with the button"}],"title":"joynedButton(_:productOfferingForRaw:)","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate\/joynedButton(_:productOfferingForRaw:)","kind":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedbuttondelegate\/joynedbutton(_:productofferingforraw:)","required":true,"role":"symbol","navigatorTitle":[{"text":"joynedButton:productOfferingForRaw:","kind":"identifier"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButtonDelegate/joynedButton(_:productOfferingForItem:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"joynedButton","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@JoynedMobileSDK@objc(cs)JoynedButton","kind":"typeIdentifier","text":"JoynedButton"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"productOfferingForItem"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"JoynedOfferingRequest","kind":"typeIdentifier","preciseIdentifier":"c:@M@JoynedMobileSDK@objc(cs)JoynedOfferingRequest"},{"text":"?","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"Called when the User clicks the button, if the button is contained within a "},{"type":"codeVoice","code":"UICollectionView"},{"type":"text","text":" and is visiable on screen"},{"text":" ","type":"text"},{"text":"Asks for the relevent product offering, provides the index path associated with the button","type":"text"}],"title":"joynedButton(_:productOfferingForItem:)","kind":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate\/joynedButton(_:productOfferingForItem:)","url":"\/documentation\/joynedmobilesdk\/joynedbuttondelegate\/joynedbutton(_:productofferingforitem:)","navigatorTitle":[{"kind":"identifier","text":"joynedButton:productOfferingForItem:"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"joynedButton:productOfferingFor:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"joynedButton:productOfferingFor:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":[{"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate\/joynedButton(_:productOfferingForRaw:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate\/joynedButton(_:productOfferingForItem:)"],"generated":true,"title":"Offering computations"}],"op":"replace","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingRequest","kind":"typeIdentifier","preciseIdentifier":"c:@M@JoynedMobileSDK@objc(cs)JoynedOfferingRequest","text":"JoynedOfferingRequest"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"joynedButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@JoynedMobileSDK@objc(cs)JoynedButton","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton","text":"JoynedButton","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"button","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"productOfferingFor:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"},{"kind":"text","text":") "},{"text":"location","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButtonDelegate\/title","value":"JoynedButtonDelegate"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButtonDelegate\/fragments","value":[{"kind":"identifier","text":"JoynedButtonDelegate"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton\/title","value":"JoynedButton"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton\/fragments","op":"replace","value":[{"text":"JoynedButton","kind":"identifier"}]},{"op":"replace","value":"JoynedOfferingRequest","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingRequest\/title"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingRequest\/fragments","op":"replace","value":[{"kind":"identifier","text":"JoynedOfferingRequest"}]},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButtonDelegate~1joynedButton(_:productOfferingFor:)\/title","op":"replace","value":"joynedButton:productOfferingFor:"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButtonDelegate~1joynedButton(_:productOfferingFor:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"joynedButton:productOfferingFor:"}]},{"value":"joynedButton:productOfferingForRaw:","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButtonDelegate~1joynedButton(_:productOfferingForRaw:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButtonDelegate~1joynedButton(_:productOfferingForRaw:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"joynedButton:productOfferingForRaw:","kind":"identifier"}]},{"value":"joynedButton:productOfferingForItem:","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButtonDelegate~1joynedButton(_:productOfferingForItem:)\/title"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButtonDelegate~1joynedButton(_:productOfferingForItem:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"joynedButton:productOfferingForItem:","kind":"identifier"}],"op":"replace"}]}]}