{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Returns an Offering Request object with imutable payload","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/joynedmobilesdk\/joynedofferingrequest\/init(offering:extra:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/joynedmobilesdk\/joynedofferingrequest\/init(offering:extra:)"]}],"kind":"symbol","seeAlsoSections":[{"generated":true,"title":"Initializers","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingRequest\/init(offeringString:extraString:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingRequest\/init(offeringDictionary:extraDictionary:)"]}],"metadata":{"modules":[{"name":"JoynedMobileSDK"}],"roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"offering"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"], ","kind":"text"},{"text":"extra","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"])","kind":"text"}],"symbolKind":"init","externalID":"c:@M@JoynedMobileSDK@objc(cs)JoynedOfferingRequest(im)initWithOffering:extra:","title":"init(offering:extra:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithOffering:extra:"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"offering","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"data","kind":"internalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"text":"extra","kind":"externalParam"},{"kind":"text","text":" "},{"text":"appdata","kind":"internalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"])","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"name":"data","content":[{"inlineContent":[{"type":"text","text":"offering data to be processed by the system, in [String: Any] format"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"extra application  data to be processed by the system, in [String: Any] format"}]}],"name":"appdata"}],"kind":"parameters"}],"identifier":{"url":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingRequest\/init(offering:extra:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/GettingStarted","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingRequest"]]},"references":{"doc://co.joyned.mobile.JoynedMobileSDK/documentation/GettingStarted":{"title":"Getting Started with Joyned mobile SDK","url":"\/documentation\/gettingstarted","type":"topic","abstract":[],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/GettingStarted","kind":"article","role":"collection"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedOfferingRequest":{"url":"\/documentation\/joynedmobilesdk\/joynedofferingrequest","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingRequest","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JoynedOfferingRequest"}],"kind":"symbol","title":"JoynedOfferingRequest","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"JoynedOfferingRequest","kind":"identifier"}],"role":"symbol"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedOfferingRequest/init(offeringDictionary:extraDictionary:)":{"abstract":[{"text":"Returns an Offering Request object with imutable payload","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithOfferingDictionary:extraDictionary:"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"offeringDictionary"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"extraDictionary"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary"},{"kind":"text","text":")"}],"role":"symbol","type":"topic","url":"\/documentation\/joynedmobilesdk\/joynedofferingrequest\/init(offeringdictionary:extradictionary:)","kind":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingRequest\/init(offeringDictionary:extraDictionary:)","title":"init(offeringDictionary:extraDictionary:)"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedOfferingRequest/init(offering:extra:)":{"url":"\/documentation\/joynedmobilesdk\/joynedofferingrequest\/init(offering:extra:)","type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingRequest\/init(offering:extra:)","navigatorTitle":[{"text":"initWithOffering:extra:","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Returns an Offering Request object with imutable payload","type":"text"}],"title":"init(offering:extra:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"offering"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"extra"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"])","kind":"text"}],"role":"symbol"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedOfferingRequest/init(offeringString:extraString:)":{"abstract":[{"text":"Returns an Offering Request object with imutable payload","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithOfferingString:extraString:"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"offeringString"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"extraString"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"role":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedofferingrequest\/init(offeringstring:extrastring:)","kind":"symbol","type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingRequest\/init(offeringString:extraString:)","title":"init(offeringString:extraString:)"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"initWithOffering:extra:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithOffering:extra:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingRequest\/init(offeringString:extraString:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingRequest\/init(offeringDictionary:extraDictionary:)"],"generated":true,"title":"Initializers"}],"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithOffering:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,id>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"data"},{"kind":"text","text":" "},{"kind":"identifier","text":"extra:"},{"text":"(","kind":"text"},{"text":"NSDictionary<NSString *,id>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"text":" *) ","kind":"text"},{"text":"appdata","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"JoynedOfferingRequest","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingRequest\/title"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingRequest\/fragments","op":"replace","value":[{"kind":"identifier","text":"JoynedOfferingRequest"}]},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingRequest~1init(offeringDictionary:extraDictionary:)\/title","value":"initWithOfferingDictionary:extraDictionary:"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingRequest~1init(offeringDictionary:extraDictionary:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithOfferingDictionary:extraDictionary:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingRequest~1init(offering:extra:)\/title","value":"initWithOffering:extra:"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingRequest~1init(offering:extra:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithOffering:extra:","kind":"identifier"}]},{"value":"initWithOfferingString:extraString:","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingRequest~1init(offeringString:extraString:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingRequest~1init(offeringString:extraString:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithOfferingString:extraString:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}