{"hierarchy":{"paths":[["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/GettingStarted","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingRequest"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"offeringDictionary","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"data","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"extraDictionary","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"appdata","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSDictionary","kind":"typeIdentifier","text":"NSDictionary"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"name":"data","content":[{"inlineContent":[{"text":"offering data to be processed by the system, in NSDictionary format","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"extra application  data to be processed by the system, in NSDictionary format"}],"type":"paragraph"}],"name":"appdata"}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/joynedmobilesdk\/joynedofferingrequest\/init(offeringdictionary:extradictionary:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/joynedmobilesdk\/joynedofferingrequest\/init(offeringdictionary:extradictionary:)"]}],"identifier":{"url":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingRequest\/init(offeringDictionary:extraDictionary:)","interfaceLanguage":"swift"},"kind":"symbol","seeAlsoSections":[{"generated":true,"title":"Initializers","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingRequest\/init(offering:extra:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingRequest\/init(offeringString:extraString:)"]}],"sections":[],"metadata":{"modules":[{"name":"JoynedMobileSDK"}],"externalID":"c:@M@JoynedMobileSDK@objc(cs)JoynedOfferingRequest(im)initWithOfferingDictionary:extraDictionary:","roleHeading":"Initializer","role":"symbol","title":"init(offeringDictionary:extraDictionary:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"offeringDictionary","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary"},{"text":", ","kind":"text"},{"text":"extraDictionary","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithOfferingDictionary:extraDictionary:","kind":"identifier"}],"symbolKind":"init"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Returns an Offering Request object with imutable payload","type":"text"}],"references":{"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedOfferingRequest/init(offeringDictionary:extraDictionary:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithOfferingDictionary:extraDictionary:"}],"role":"symbol","title":"init(offeringDictionary:extraDictionary:)","type":"topic","abstract":[{"text":"Returns an Offering Request object with imutable payload","type":"text"}],"url":"\/documentation\/joynedmobilesdk\/joynedofferingrequest\/init(offeringdictionary:extradictionary:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"offeringDictionary"},{"kind":"text","text":": "},{"text":"NSDictionary","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":", "},{"kind":"externalParam","text":"extraDictionary"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary"},{"text":")","kind":"text"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingRequest\/init(offeringDictionary:extraDictionary:)"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedOfferingRequest/init(offering:extra:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithOffering:extra:"}],"role":"symbol","title":"init(offering:extra:)","type":"topic","abstract":[{"type":"text","text":"Returns an Offering Request object with imutable payload"}],"kind":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedofferingrequest\/init(offering:extra:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"offering"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"extra"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"])","kind":"text"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingRequest\/init(offering:extra:)"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedOfferingRequest":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"JoynedOfferingRequest","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"JoynedOfferingRequest","kind":"identifier"}],"role":"symbol","abstract":[],"url":"\/documentation\/joynedmobilesdk\/joynedofferingrequest","type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingRequest","title":"JoynedOfferingRequest"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/GettingStarted":{"kind":"article","role":"collection","url":"\/documentation\/gettingstarted","type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/GettingStarted","title":"Getting Started with Joyned mobile SDK","abstract":[]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedOfferingRequest/init(offeringString:extraString:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithOfferingString:extraString:"}],"role":"symbol","title":"init(offeringString:extraString:)","type":"topic","abstract":[{"text":"Returns an Offering Request object with imutable payload","type":"text"}],"url":"\/documentation\/joynedmobilesdk\/joynedofferingrequest\/init(offeringstring:extrastring:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"offeringString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"extraString"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingRequest\/init(offeringString:extraString:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"initWithOfferingDictionary:extraDictionary:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithOfferingDictionary:extraDictionary:"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"replace","value":[{"title":"Initializers","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingRequest\/init(offering:extra:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingRequest\/init(offeringString:extraString:)"],"generated":true}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithOfferingDictionary:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"data"},{"text":" ","kind":"text"},{"text":"extraDictionary:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSDictionary","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":" *) "},{"text":"appdata","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingRequest~1init(offeringDictionary:extraDictionary:)\/title","value":"initWithOfferingDictionary:extraDictionary:","op":"replace"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingRequest~1init(offeringDictionary:extraDictionary:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithOfferingDictionary:extraDictionary:"}],"op":"replace"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingRequest~1init(offering:extra:)\/title","op":"replace","value":"initWithOffering:extra:"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingRequest~1init(offering:extra:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithOffering:extra:"}]},{"value":"JoynedOfferingRequest","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingRequest\/title","op":"replace"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingRequest\/fragments","op":"replace","value":[{"text":"JoynedOfferingRequest","kind":"identifier"}]},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingRequest~1init(offeringString:extraString:)\/title","value":"initWithOfferingString:extraString:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingRequest~1init(offeringString:extraString:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithOfferingString:extraString:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}