{"metadata":{"title":"Getting Started with Joyned mobile SDK","role":"collection"},"kind":"article","hierarchy":{"paths":[[]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/GettingStarted","interfaceLanguage":"swift"},"sections":[],"topicSections":[{"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/installation","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/activation","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/global_delegate","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/screen_llst","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate"],"title":"Essentials"},{"title":"Hosted Joyned UI","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/hosted_ui","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate"]},{"title":"Invetation link API","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/invitation_links"]},{"title":"Offering Related API","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/offering","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingRequest","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingResponse"]},{"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/transaction","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedTransactionRequest"],"title":"Transaction report API"},{"title":"Advance usage API","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/advance"]},{"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/j_throw_objc(_:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/j_try_objc(_:_:_:)"],"title":"Objective-C Utilities"},{"title":"UIKit Utilities","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/UIKit\/UIWindow","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/UIKit\/UIViewController"]},{"title":"Type Alias","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedAreaComputation"]}],"references":{"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/UIKit/UIViewController":{"abstract":[{"text":"Public extensions of JoynedMobileSDK for simplier code usage","type":"text"}],"url":"\/documentation\/joynedmobilesdk\/uikit\/uiviewcontroller","fragments":[{"text":"extension","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"title":"UIViewController","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/UIKit\/UIViewController","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"UIViewController","kind":"identifier"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"JoynedButton","kind":"identifier"}],"title":"JoynedButton","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton","kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/joynedmobilesdk\/joynedbutton","role":"symbol","navigatorTitle":[{"text":"JoynedButton","kind":"identifier"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButtonDelegate":{"abstract":[],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate","url":"\/documentation\/joynedmobilesdk\/joynedbuttondelegate","type":"topic","title":"JoynedButtonDelegate","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JoynedButtonDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"JoynedButtonDelegate"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/j_try_objc(_:_:_:)":{"title":"j_try_objc(_:_:_:)","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/j_try_objc(_:_:_:)","url":"\/documentation\/joynedmobilesdk\/j_try_objc(_:_:_:)","abstract":[{"type":"text","text":"Execute Swift code that could generate an Objective-C exception in here to catch and handle it gracefully (ie don’t crash)"}],"navigatorTitle":[{"text":"j_try_objc","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"j_try_objc","kind":"identifier"},{"kind":"text","text":"(() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":", (","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSException","text":"NSException","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":", () -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JoynedSDK"}],"title":"JoynedSDK","kind":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedsdk","navigatorTitle":[{"kind":"identifier","text":"JoynedSDK"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK","type":"topic","abstract":[{"type":"text","text":"The main public access class to ther Joyned mobile SDK, use it to interact with the system"}],"role":"symbol"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/hosted_ui":{"url":"\/documentation\/joynedmobilesdk\/hosted_ui","kind":"article","type":"topic","abstract":[{"type":"text","text":"Hosted Joyned UI"},{"text":" ","type":"text"},{"text":"Joyned mobile SDK provides a few views which are ment to be used within application that hosts the SDK","type":"text"}],"title":"Hosted UI","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/hosted_ui","role":"article"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/transaction":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/transaction","abstract":[{"type":"text","text":"API to make joyned is aware of all purchase transactions processed by your application."}],"role":"article","title":"Report transaction","url":"\/documentation\/joynedmobilesdk\/transaction","kind":"article","type":"topic"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedAreaComputation":{"kind":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedAreaComputation","role":"symbol","title":"JoynedAreaComputation","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"JoynedAreaComputation","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"JoynedAreaComputation","kind":"identifier"}],"url":"\/documentation\/joynedmobilesdk\/joynedareacomputation","abstract":[{"text":"A helper type used for dynamic drag area computations","type":"text"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/global_delegate":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/global_delegate","url":"\/documentation\/joynedmobilesdk\/global_delegate","kind":"article","abstract":[{"text":"Joyned mobile SDK provides several intervention hooks via the ","type":"text"},{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate","isActive":true,"type":"reference"},{"text":" protocol","type":"text"}],"role":"article","title":"Global Delegate","type":"topic"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/advance":{"title":"Advance SDK configuration","kind":"article","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/advance","abstract":[{"type":"text","text":"Extra options to configure SDK sub-elements"}],"url":"\/documentation\/joynedmobilesdk\/advance","type":"topic","role":"article"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/offering":{"type":"topic","title":"Offering handling API","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/offering","abstract":[{"type":"text","text":"API for interacting with JoynedMobileSDK offerings"}],"role":"article","url":"\/documentation\/joynedmobilesdk\/offering","kind":"article"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDKDelegate":{"abstract":[{"type":"text","text":"Implement this to recive notifications on major actions taken by the SDK and affect its behavior"}],"navigatorTitle":[{"kind":"identifier","text":"JoynedSDKDelegate"}],"kind":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedsdkdelegate","title":"JoynedSDKDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JoynedSDKDelegate","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/invitation_links":{"type":"topic","abstract":[{"type":"text","text":"Handle supported deeplinks for Joyned content"}],"title":"Joyned Session invitation links","url":"\/documentation\/joynedmobilesdk\/invitation_links","role":"article","kind":"article","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/invitation_links"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedTransactionRequest":{"kind":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedTransactionRequest","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JoynedTransactionRequest"}],"navigatorTitle":[{"kind":"identifier","text":"JoynedTransactionRequest"}],"url":"\/documentation\/joynedmobilesdk\/joynedtransactionrequest","type":"topic","title":"JoynedTransactionRequest","abstract":[]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/activation":{"url":"\/documentation\/joynedmobilesdk\/activation","abstract":[{"text":"There are several different ways to activate of the Joyned mobile SDK","type":"text"}],"type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/activation","title":"Activation Methods","kind":"article","role":"article"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedOfferingRequest":{"url":"\/documentation\/joynedmobilesdk\/joynedofferingrequest","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingRequest","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JoynedOfferingRequest"}],"kind":"symbol","title":"JoynedOfferingRequest","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"JoynedOfferingRequest","kind":"identifier"}],"role":"symbol"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/installation":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/installation","abstract":[{"type":"text","text":"How to install this library"}],"role":"article","kind":"article","title":"Library installation","url":"\/documentation\/joynedmobilesdk\/installation","type":"topic"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/j_throw_objc(_:)":{"title":"j_throw_objc(_:)","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/j_throw_objc(_:)","url":"\/documentation\/joynedmobilesdk\/j_throw_objc(_:)","abstract":[{"type":"text","text":"Throws an Objective-C exception"}],"navigatorTitle":[{"kind":"identifier","text":"j_throw_objc"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"j_throw_objc","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSException","text":"NSException","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedOfferingResponse":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"JoynedOfferingResponse"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"JoynedOfferingResponse","kind":"identifier"}],"role":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedofferingresponse","kind":"symbol","type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingResponse","title":"JoynedOfferingResponse"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/UIKit/UIWindow":{"url":"\/documentation\/joynedmobilesdk\/uikit\/uiwindow","abstract":[{"text":"Public extensions of JoynedMobileSDK for simplier code usage","type":"text"}],"navigatorTitle":[{"text":"UIWindow","kind":"identifier"}],"title":"UIWindow","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/UIKit\/UIWindow","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"preciseIdentifier":"c:objc(cs)UIWindow","text":"UIWindow","kind":"identifier"}],"role":"symbol"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/screen_llst":{"title":"Screen Validation Controls","kind":"article","type":"topic","role":"article","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/screen_llst","abstract":[{"type":"text","text":"Joyned Mobile SDK screen change monitor"}],"url":"\/documentation\/joynedmobilesdk\/screen_llst"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton\/title","value":"JoynedButton"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton\/fragments","value":[{"kind":"identifier","text":"JoynedButton"}]},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButtonDelegate\/title","op":"replace","value":"JoynedButtonDelegate"},{"op":"replace","value":[{"text":"JoynedButtonDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButtonDelegate\/fragments"},{"value":"j_try_objc","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1j_try_objc(_:_:_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1j_try_objc(_:_:_:)\/fragments","op":"replace","value":[{"kind":"identifier","text":"j_try_objc"}]},{"value":"JoynedSDK","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK\/title","op":"replace"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK\/fragments","op":"replace","value":[{"kind":"identifier","text":"JoynedSDK"}]},{"value":"JoynedSDKDelegate","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDKDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDKDelegate\/fragments","value":[{"kind":"identifier","text":"JoynedSDKDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedTransactionRequest\/title","value":"JoynedTransactionRequest"},{"op":"replace","value":[{"kind":"identifier","text":"JoynedTransactionRequest"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedTransactionRequest\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingRequest\/title","value":"JoynedOfferingRequest"},{"op":"replace","value":[{"text":"JoynedOfferingRequest","kind":"identifier"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingRequest\/fragments"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1j_throw_objc(_:)\/title","value":"j_throw_objc","op":"replace"},{"value":[{"text":"j_throw_objc","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1j_throw_objc(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingResponse\/title","value":"JoynedOfferingResponse"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingResponse\/fragments","value":[{"text":"JoynedOfferingResponse","kind":"identifier"}]}]}]}