{"metadata":{"role":"collection","externalID":"JoynedMobileSDK","title":"JoynedMobileSDK","roleHeading":"Framework","symbolKind":"module","modules":[{"name":"JoynedMobileSDK"}]},"hierarchy":{"paths":[[]]},"abstract":[{"text":"We help people book together. With a better booking experience, better business results","type":"text"}],"primaryContentSections":[{"kind":"content","content":[{"type":"heading","level":2,"text":"Overview","anchor":"Overview"},{"inlineContent":[{"type":"text","text":"Friends who travel together make decisions together. Why not let them book together?"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"Joyned allows people to invite friends to your website or app, book together and interact LIVE, on-site.","type":"text"}]},{"level":3,"type":"heading","text":"Featured","anchor":"Featured"},{"style":"detailedGrid","items":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSample"],"type":"links"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/joynedmobilesdk"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/joynedmobilesdk"]}],"topicSections":[{"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSample"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","references":{"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedMobileSDKVersionNumber":{"type":"topic","abstract":[{"type":"text","text":"Project version number for JoynedMobileSDK."}],"role":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedmobilesdkversionnumber","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedMobileSDKVersionNumber","title":"JoynedMobileSDKVersionNumber","fragments":[{"text":"JoynedMobileSDKVersionNumber","kind":"identifier"}],"kind":"symbol"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedMobileSDKVersionString":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedMobileSDKVersionString","role":"symbol","abstract":[{"type":"text","text":"Project version string for JoynedMobileSDK."}],"fragments":[{"text":"JoynedMobileSDKVersionString","kind":"identifier"}],"title":"JoynedMobileSDKVersionString","url":"\/documentation\/joynedmobilesdk\/joynedmobilesdkversionstring","kind":"symbol","type":"topic"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/GettingStarted":{"url":"\/documentation\/joynedmobilesdk\/gettingstarted","title":"Getting Started with Joyned mobile SDK","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","type":"topic","abstract":[],"kind":"article","role":"collectionGroup"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK":{"url":"\/documentation\/joynedmobilesdk","title":"JoynedMobileSDK","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","type":"topic","abstract":[{"text":"We help people book together. With a better booking experience, better business results","type":"text"}],"kind":"symbol","role":"collection"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSample":{"type":"topic","abstract":[{"type":"text","text":"Integrate JoynedMobileSDK into an iOS app for booking and ordering togather."}],"role":"sampleCode","url":"\/documentation\/joynedmobilesdk\/joynedsample","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSample","title":"Sample code - Voyage App","kind":"article"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":[{"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSample"]},{"title":"Variables","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedMobileSDKVersionNumber","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedMobileSDKVersionString"]}],"path":"\/topicSections","op":"replace"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"}],"traits":[{"interfaceLanguage":"occ"}]}]}