{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/append(WhiteList:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"append"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"WhiteList"},{"kind":"text","text":" "},{"kind":"internalParam","text":"screen"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"new screen name to add to the valid screens list"}],"type":"paragraph"}],"name":"screen"}]},{"content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Note: If no screens are in the white list the system will ignore its limitations"}]}],"kind":"content"}],"seeAlsoSections":[{"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/remove(WhiteList:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/append(BlackList:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/remove(BlackList:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/clearScreensBlackList()","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/screen_llst"],"title":"SDK Screen Validation","generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/joynedmobilesdk\/joynedsdk\/append(whitelist:)"]},{"paths":["\/documentation\/joynedmobilesdk\/joynedsdk\/append(whitelist:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Use this method to add a new screen name to the system white list"},{"text":" ","type":"text"},{"text":"On screens which appear in the whitelist the Joyned mobile SDK will present it’s floating content,","type":"text"}],"metadata":{"externalID":"c:@M@JoynedMobileSDK@objc(cs)JoynedSDK(cm)appendWithWhiteList:","roleHeading":"Type Method","role":"symbol","symbolKind":"method","title":"append(WhiteList:)","modules":[{"name":"JoynedMobileSDK"}],"navigatorTitle":[{"text":"appendWithWhiteList:","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"append","kind":"identifier"},{"text":"(","kind":"text"},{"text":"WhiteList","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}]},"references":{"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/screen_llst":{"type":"topic","kind":"article","abstract":[{"type":"text","text":"Joyned Mobile SDK screen change monitor"}],"url":"\/documentation\/joynedmobilesdk\/screen_llst","title":"Screen Validation Controls","role":"article","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/screen_llst"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK/clearScreensBlackList()":{"type":"topic","abstract":[{"type":"text","text":"Use this method to clear the invalid screen names from the system black list"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"clearScreensBlackList","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/clearScreensBlackList()","navigatorTitle":[{"text":"clearScreensBlackList","kind":"identifier"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdk\/clearscreensblacklist()","kind":"symbol","role":"symbol","title":"clearScreensBlackList()"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK/remove(WhiteList:)":{"type":"topic","abstract":[{"type":"text","text":"Use this method to remove a screen name to the system white list"},{"type":"text","text":" "},{"type":"text","text":"On screens which appear in the whitelist the Joyned mobile SDK will present it’s floating content,"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"remove"},{"kind":"text","text":"("},{"text":"WhiteList","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/remove(WhiteList:)","navigatorTitle":[{"text":"removeWithWhiteList:","kind":"identifier"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdk\/remove(whitelist:)","kind":"symbol","role":"symbol","title":"remove(WhiteList:)"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK/remove(BlackList:)":{"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Use this method to remove a  screen name to the system black list"},{"type":"text","text":" "},{"type":"text","text":"On screens which appear in the blacklist the Joyned mobile SDK will not present it’s floating content,"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdk\/remove(blacklist:)","navigatorTitle":[{"kind":"identifier","text":"removeWithBlackList:"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"remove"},{"text":"(","kind":"text"},{"text":"BlackList","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"remove(BlackList:)","role":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/remove(BlackList:)"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/GettingStarted":{"url":"\/documentation\/joynedmobilesdk\/gettingstarted","title":"Getting Started with Joyned mobile SDK","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","type":"topic","abstract":[],"kind":"article","role":"collectionGroup"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK":{"type":"topic","abstract":[{"type":"text","text":"The main public access class to ther Joyned mobile SDK, use it to interact with the system"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JoynedSDK"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK","navigatorTitle":[{"text":"JoynedSDK","kind":"identifier"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdk","kind":"symbol","role":"symbol","title":"JoynedSDK"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK/append(WhiteList:)":{"type":"topic","abstract":[{"type":"text","text":"Use this method to add a new screen name to the system white list"},{"type":"text","text":" "},{"type":"text","text":"On screens which appear in the whitelist the Joyned mobile SDK will present it’s floating content,"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"append"},{"kind":"text","text":"("},{"text":"WhiteList","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/append(WhiteList:)","navigatorTitle":[{"text":"appendWithWhiteList:","kind":"identifier"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdk\/append(whitelist:)","kind":"symbol","role":"symbol","title":"append(WhiteList:)"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK/append(BlackList:)":{"type":"topic","abstract":[{"text":"Use this method to add a new screen name to the system black list","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"On screens which appear in the blacklist the Joyned mobile SDK will not present it’s floating content,"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"append","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BlackList","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/append(BlackList:)","navigatorTitle":[{"text":"appendWithBlackList:","kind":"identifier"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdk\/append(blacklist:)","kind":"symbol","role":"symbol","title":"append(BlackList:)"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK":{"url":"\/documentation\/joynedmobilesdk","title":"JoynedMobileSDK","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","type":"topic","abstract":[{"text":"We help people book together. With a better booking experience, better business results","type":"text"}],"kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"value":"appendWithWhiteList:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"appendWithWhiteList:"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":[{"generated":true,"title":"SDK Screen Validation","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/remove(WhiteList:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/append(BlackList:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/remove(BlackList:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/clearScreensBlackList()","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/screen_llst"]}],"path":"\/seeAlsoSections","op":"replace"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"appendWithWhiteList:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"screen"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1clearScreensBlackList()\/title","op":"replace","value":"clearScreensBlackList"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1clearScreensBlackList()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"clearScreensBlackList","kind":"identifier"}]},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1remove(WhiteList:)\/title","op":"replace","value":"removeWithWhiteList:"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"removeWithWhiteList:"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1remove(WhiteList:)\/fragments","op":"replace"},{"value":"removeWithBlackList:","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1remove(BlackList:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"removeWithBlackList:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1remove(BlackList:)\/fragments"},{"value":"JoynedSDK","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK\/title"},{"value":[{"text":"JoynedSDK","kind":"identifier"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1append(WhiteList:)\/title","value":"appendWithWhiteList:"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1append(WhiteList:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"appendWithWhiteList:"}]},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1append(BlackList:)\/title","value":"appendWithBlackList:"},{"value":[{"text":"+ ","kind":"text"},{"text":"appendWithBlackList:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1append(BlackList:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}