{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/delegate"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/joynedmobilesdk\/joynedsdk\/delegate"]},{"paths":["\/documentation\/joynedmobilesdk\/joynedsdk\/delegate"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/GettingStarted","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK"]]},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"The delegate of the SDK used for general control hooks into the system."}],"metadata":{"title":"delegate","modules":[{"name":"JoynedMobileSDK"}],"roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:@M@JoynedMobileSDK@objc(cs)JoynedSDK(cpy)delegate","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@JoynedMobileSDK@objc(pl)JoynedSDKDelegate","kind":"typeIdentifier","text":"JoynedSDKDelegate"},{"text":"?","kind":"text"}]},"seeAlsoSections":[{"title":"Properties","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/libraryVersion","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/global_delegate"],"generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"weak","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@JoynedMobileSDK@objc(pl)JoynedSDKDelegate","kind":"typeIdentifier","text":"JoynedSDKDelegate","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://co.joyned.mobile.JoynedMobileSDK/documentation/GettingStarted":{"title":"Getting Started with Joyned mobile SDK","url":"\/documentation\/gettingstarted","type":"topic","abstract":[],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/GettingStarted","kind":"article","role":"collection"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK/libraryVersion":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/libraryVersion","url":"\/documentation\/joynedmobilesdk\/joynedsdk\/libraryversion","abstract":[{"type":"text","text":"Returns the SDK version in the following template "},{"type":"codeVoice","code":"x.y.z (buildNumber)"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"libraryVersion"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","title":"libraryVersion","type":"topic","navigatorTitle":[{"text":"libraryVersion","kind":"identifier"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/global_delegate":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/global_delegate","url":"\/documentation\/joynedmobilesdk\/global_delegate","kind":"article","abstract":[{"text":"Joyned mobile SDK provides several intervention hooks via the ","type":"text"},{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate","isActive":true,"type":"reference"},{"text":" protocol","type":"text"}],"role":"article","title":"Global Delegate","type":"topic"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDKDelegate":{"abstract":[{"type":"text","text":"Implement this to recive notifications on major actions taken by the SDK and affect its behavior"}],"navigatorTitle":[{"kind":"identifier","text":"JoynedSDKDelegate"}],"kind":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedsdkdelegate","title":"JoynedSDKDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JoynedSDKDelegate","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK/delegate":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/delegate","url":"\/documentation\/joynedmobilesdk\/joynedsdk\/delegate","abstract":[{"text":"The delegate of the SDK used for general control hooks into the system.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JoynedSDKDelegate","preciseIdentifier":"c:@M@JoynedMobileSDK@objc(pl)JoynedSDKDelegate"},{"kind":"text","text":"?"}],"role":"symbol","title":"delegate","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JoynedSDK"}],"title":"JoynedSDK","kind":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedsdk","navigatorTitle":[{"kind":"identifier","text":"JoynedSDK"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK","type":"topic","abstract":[{"type":"text","text":"The main public access class to ther Joyned mobile SDK, use it to interact with the system"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"value":"delegate","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"delegate","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"replace","value":[{"generated":true,"title":"Properties","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/libraryVersion"]}],"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"weak","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@JoynedMobileSDK@objc(pl)JoynedSDKDelegate","text":"id<JoynedSDKDelegate>"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1libraryVersion\/title","value":"libraryVersion","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"libraryVersion"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1libraryVersion\/fragments"},{"value":"JoynedSDKDelegate","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDKDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDKDelegate\/fragments","value":[{"text":"JoynedSDKDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1delegate\/title","op":"replace","value":"delegate"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1delegate\/fragments","value":[{"text":"delegate","kind":"identifier"}],"op":"replace"},{"value":"JoynedSDK","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK\/title"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK\/fragments","value":[{"text":"JoynedSDK","kind":"identifier"}],"op":"replace"}]}]}