{"sections":[],"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/_02_hosted-ui"],"title":"SDK Hosted UI"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@discardableResult","kind":"attribute"},{"kind":"text","text":" "},{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"generateJoynedButton"},{"text":"(","kind":"text"},{"text":"frame","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"kind":"text","text":" = CGRect.zero, "},{"text":"with","kind":"externalParam"},{"kind":"text","text":" "},{"text":"delegate","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JoynedMobileSDK@objc(pl)JoynedButtonDelegate","kind":"typeIdentifier","text":"JoynedButtonDelegate","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate"},{"text":"? = nil) -> ","kind":"text"},{"text":"JoynedButton","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton","preciseIdentifier":"c:@M@JoynedMobileSDK@objc(cs)JoynedButton","kind":"typeIdentifier"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The frame of the new view in it’s parent coorinate space","type":"text"}],"type":"paragraph"}],"name":"frame"}]},{"kind":"content","content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"inlineContent":[{"type":"text","text":"New intance of "},{"type":"reference","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton","isActive":true}],"type":"paragraph"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/generateJoynedButton(frame:with:)"},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"generateJoynedButton","kind":"identifier"},{"text":"(","kind":"text"},{"text":"frame","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@JoynedMobileSDK@objc(pl)JoynedButtonDelegate","kind":"typeIdentifier","text":"JoynedButtonDelegate"},{"kind":"text","text":"?) -> "},{"text":"JoynedButton","kind":"typeIdentifier","preciseIdentifier":"c:@M@JoynedMobileSDK@objc(cs)JoynedButton"}],"modules":[{"name":"JoynedMobileSDK"}],"title":"generateJoynedButton(frame:with:)","navigatorTitle":[{"kind":"identifier","text":"generateJoynedButtonWithFrame:with:"}],"symbolKind":"method","roleHeading":"Type Method","externalID":"c:@M@JoynedMobileSDK@objc(cs)JoynedSDK(cm)generateJoynedButtonWithFrame:with:","role":"symbol"},"abstract":[{"type":"text","text":"Use this method to generate a new instance of "},{"isActive":true,"type":"reference","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/joynedmobilesdk\/joynedsdk\/generatejoynedbutton(frame:with:)"]},{"paths":["\/documentation\/joynedmobilesdk\/joynedsdk\/generatejoynedbutton(frame:with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK"],["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/GettingStarted":{"title":"Getting Started with Joyned mobile SDK","abstract":[],"type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","role":"collectionGroup","url":"\/documentation\/joynedmobilesdk\/gettingstarted","kind":"article"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton":{"title":"JoynedButton","abstract":[{"type":"text","text":"A Joyned UI element meant for usage in the host application, acts as a card like display element, supports border, shadow, corner cliping & more"}],"type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton","role":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedbutton","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"JoynedButton","kind":"identifier"}],"navigatorTitle":[{"text":"JoynedButton","kind":"identifier"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButtonDelegate":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate","navigatorTitle":[{"kind":"identifier","text":"JoynedButtonDelegate"}],"title":"JoynedButtonDelegate","url":"\/documentation\/joynedmobilesdk\/joynedbuttondelegate","abstract":[{"type":"text","text":"Methods for managing JoynedButton behavior, allows the system a way to pass navigation requests & more"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"JoynedButtonDelegate"}],"type":"topic"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK":{"title":"JoynedMobileSDK","abstract":[{"text":"We help people book together. With a better booking experience, better business results","type":"text"}],"type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","role":"collection","url":"\/documentation\/joynedmobilesdk","kind":"symbol"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK":{"title":"JoynedSDK","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The main public access class to ther Joyned mobile SDK, use it to interact with the system"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdk","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JoynedSDK"}],"navigatorTitle":[{"text":"JoynedSDK","kind":"identifier"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/_02_hosted-ui":{"kind":"article","role":"article","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/_02_hosted-ui","title":"Hosted UI","url":"\/documentation\/joynedmobilesdk\/_02_hosted-ui","abstract":[{"type":"text","text":"Hosted Joyned UI"},{"type":"text","text":" "},{"type":"text","text":"Joyned mobile SDK provides a few views which are ment to be used within application that hosts the SDK"}],"type":"topic"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK/generateJoynedButton(frame:with:)":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/generateJoynedButton(frame:with:)","navigatorTitle":[{"text":"generateJoynedButtonWithFrame:with:","kind":"identifier"}],"title":"generateJoynedButton(frame:with:)","url":"\/documentation\/joynedmobilesdk\/joynedsdk\/generatejoynedbutton(frame:with:)","abstract":[{"type":"text","text":"Use this method to generate a new instance of "},{"type":"reference","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton","isActive":true}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"generateJoynedButton","kind":"identifier"},{"text":"(","kind":"text"},{"text":"frame","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"text":"JoynedButtonDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@JoynedMobileSDK@objc(pl)JoynedButtonDelegate"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:@M@JoynedMobileSDK@objc(cs)JoynedButton","text":"JoynedButton","kind":"typeIdentifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"generateJoynedButtonWithFrame:with:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"generateJoynedButtonWithFrame:with:"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"replace","value":[{"title":"SDK Hosted UI","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/_02_hosted-ui"],"generated":true}]},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:@M@JoynedMobileSDK@objc(cs)JoynedButton","kind":"typeIdentifier","text":"JoynedButton","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"generateJoynedButtonWithFrame:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"text":") ","kind":"text"},{"text":"frame","kind":"internalParam"},{"kind":"text","text":" "},{"text":"with:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<JoynedButtonDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@JoynedMobileSDK@objc(pl)JoynedButtonDelegate"},{"kind":"text","text":") "},{"kind":"internalParam","text":"delegate"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"value":"JoynedButton","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton\/title"},{"value":[{"text":"JoynedButton","kind":"identifier"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButtonDelegate\/title","op":"replace","value":"JoynedButtonDelegate"},{"value":[{"kind":"identifier","text":"JoynedButtonDelegate"}],"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButtonDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK\/title","value":"JoynedSDK"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK\/fragments","value":[{"text":"JoynedSDK","kind":"identifier"}],"op":"replace"},{"value":"generateJoynedButtonWithFrame:with:","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1generateJoynedButton(frame:with:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1generateJoynedButton(frame:with:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"generateJoynedButtonWithFrame:with:","kind":"identifier"}]}]}]}