{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"report"},{"kind":"text","text":"("},{"kind":"externalParam","text":"Transaction"},{"text":" ","kind":"text"},{"text":"request","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedTransactionRequest","kind":"typeIdentifier","text":"JoynedTransactionRequest","preciseIdentifier":"c:@M@JoynedMobileSDK@objc(cs)JoynedTransactionRequest"},{"kind":"text","text":"?)"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"request","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"a transaction object"}]}]}]}],"kind":"symbol","metadata":{"symbolKind":"method","role":"symbol","roleHeading":"Type Method","navigatorTitle":[{"text":"reportWithTransaction:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"report"},{"kind":"text","text":"("},{"kind":"externalParam","text":"Transaction"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JoynedMobileSDK@objc(cs)JoynedTransactionRequest","text":"JoynedTransactionRequest"},{"kind":"text","text":"?)"}],"title":"report(Transaction:)","externalID":"c:@M@JoynedMobileSDK@objc(cs)JoynedSDK(cm)reportWithTransaction:","modules":[{"name":"JoynedMobileSDK"}]},"identifier":{"url":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/report(Transaction:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/GettingStarted","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK"]]},"abstract":[{"type":"text","text":"Call this method to report purchase transactions to the Joyned SDK"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/joynedmobilesdk\/joynedsdk\/report(transaction:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/joynedmobilesdk\/joynedsdk\/report(transaction:)"]}],"seeAlsoSections":[{"title":"SDK Report transaction API","generated":true,"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/transaction"]}],"sections":[],"references":{"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/transaction":{"role":"article","url":"\/documentation\/joynedmobilesdk\/transaction","title":"Report transaction","type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/transaction","kind":"article","abstract":[{"type":"text","text":"API to make joyned is aware of all purchase transactions processed by your application."}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK/report(Transaction:)":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/report(Transaction:)","abstract":[{"type":"text","text":"Call this method to report purchase transactions to the Joyned SDK"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"reportWithTransaction:"}],"kind":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedsdk\/report(transaction:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"report"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"Transaction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JoynedMobileSDK@objc(cs)JoynedTransactionRequest","text":"JoynedTransactionRequest"},{"kind":"text","text":"?)"}],"type":"topic","title":"report(Transaction:)"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK":{"navigatorTitle":[{"kind":"identifier","text":"JoynedSDK"}],"abstract":[{"type":"text","text":"The main public access class to ther Joyned mobile SDK, use it to interact with the system"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdk","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"JoynedSDK","kind":"identifier"}],"role":"symbol","type":"topic","title":"JoynedSDK","kind":"symbol"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/GettingStarted":{"abstract":[],"type":"topic","kind":"article","role":"collection","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/GettingStarted","url":"\/documentation\/gettingstarted","title":"Getting Started with Joyned mobile SDK"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedTransactionRequest":{"navigatorTitle":[{"kind":"identifier","text":"JoynedTransactionRequest"}],"abstract":[],"url":"\/documentation\/joynedmobilesdk\/joynedtransactionrequest","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedTransactionRequest","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"JoynedTransactionRequest","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","title":"JoynedTransactionRequest"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"reportWithTransaction:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"reportWithTransaction:"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"reportWithTransaction:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedTransactionRequest","text":"JoynedTransactionRequest","preciseIdentifier":"c:@M@JoynedMobileSDK@objc(cs)JoynedTransactionRequest"},{"text":" *) ","kind":"text"},{"text":"request","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"reportWithTransaction:","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1report(Transaction:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"reportWithTransaction:","kind":"identifier"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1report(Transaction:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK\/title","value":"JoynedSDK","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK\/fragments","value":[{"kind":"identifier","text":"JoynedSDK"}]},{"op":"replace","value":"JoynedTransactionRequest","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedTransactionRequest\/title"},{"op":"replace","value":[{"text":"JoynedTransactionRequest","kind":"identifier"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedTransactionRequest\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}