{"hierarchy":{"paths":[["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK"],["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"role":"symbol","roleHeading":"Type Method","title":"scene(_:openURLContexts:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"scene","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIScene","text":"UIScene","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"openURLContexts"},{"text":": ","kind":"text"},{"text":"Set","preciseIdentifier":"s:Sh","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIOpenURLContext","text":"UIOpenURLContext"},{"text":">) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"scene:openURLContexts:"}],"externalID":"c:@M@JoynedMobileSDK@objc(cs)JoynedSDK(cm)scene:openURLContexts:","symbolKind":"method","modules":[{"name":"JoynedMobileSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@discardableResult","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scene"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"scene"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIScene","preciseIdentifier":"c:objc(cs)UIScene"},{"kind":"text","text":", "},{"kind":"externalParam","text":"openURLContexts"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"URLContexts"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sh","text":"Set"},{"text":"<","kind":"text"},{"text":"UIOpenURLContext","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIOpenURLContext"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"scene","content":[{"inlineContent":[{"type":"text","text":"The scene object being connected to your app."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"One or more UIOpenURLContext objects."},{"type":"text","text":" "},{"type":"text","text":"Each object contains one URL to open and any additional information needed to open that URL."}]}],"name":"URLContexts"}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"inlineContent":[{"type":"text","text":"true if the connectionOptions payload contains Joyned related code, otherwise false"}],"type":"paragraph"}]},{"content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"codeListing","syntax":null,"code":["Note: This method handles the case where a deeplink (custom schema) is clicked while the host application is already running"]}],"kind":"content"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/joynedmobilesdk\/joynedsdk\/scene(_:openurlcontexts:)"]},{"paths":["\/documentation\/joynedmobilesdk\/joynedsdk\/scene(_:openurlcontexts:)"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"title":"SDK - invitation links","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/scene(_:continue:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/scene(_:willConnectTo:options:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/_03_invitation-links"],"generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/scene(_:openURLContexts:)"},"abstract":[{"type":"text","text":"Call this method from the "},{"identifier":"https:\/\/developer.apple.com\/documentation\/uikit\/uiscenedelegate\/3238059-scene\/","isActive":true,"type":"reference"},{"text":" ","type":"text"},{"type":"text","text":"method of your application scene delegate. It should be invoked for the proper processing of Joyned related content."}],"references":{"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK":{"title":"JoynedMobileSDK","abstract":[{"text":"We help people book together. With a better booking experience, better business results","type":"text"}],"type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","role":"collection","url":"\/documentation\/joynedmobilesdk","kind":"symbol"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK":{"title":"JoynedSDK","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The main public access class to ther Joyned mobile SDK, use it to interact with the system"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdk","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JoynedSDK"}],"navigatorTitle":[{"text":"JoynedSDK","kind":"identifier"}]},"https://developer.apple.com/documentation/uikit/uiscenedelegate/3238059-scene/":{"title":"UISceneDelegate.scene(_:openURLContexts:)","titleInlineContent":[{"type":"codeVoice","code":"UISceneDelegate.scene(_:openURLContexts:)"}],"identifier":"https:\/\/developer.apple.com\/documentation\/uikit\/uiscenedelegate\/3238059-scene\/","url":"https:\/\/developer.apple.com\/documentation\/uikit\/uiscenedelegate\/3238059-scene\/","type":"link"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK/scene(_:openURLContexts:)":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/scene(_:openURLContexts:)","navigatorTitle":[{"text":"scene:openURLContexts:","kind":"identifier"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdk\/scene(_:openurlcontexts:)","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"scene"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIScene","text":"UIScene","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"openURLContexts","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"text":"UIOpenURLContext","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIOpenURLContext"},{"text":">) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","abstract":[{"type":"text","text":"Call this method from the "},{"isActive":true,"type":"reference","identifier":"https:\/\/developer.apple.com\/documentation\/uikit\/uiscenedelegate\/3238059-scene\/"},{"type":"text","text":" "},{"type":"text","text":"method of your application scene delegate. It should be invoked for the proper processing of Joyned related content."}],"title":"scene(_:openURLContexts:)","kind":"symbol"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK/scene(_:continue:)":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/scene(_:continue:)","navigatorTitle":[{"text":"scene:continue:","kind":"identifier"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdk\/scene(_:continue:)","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"scene","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIScene","text":"UIScene","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"continue"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSUserActivity","text":"NSUserActivity","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","abstract":[{"type":"text","text":"Call this method from the "},{"type":"reference","isActive":true,"identifier":"https:\/\/developer.apple.com\/documentation\/uikit\/uiscenedelegate\/3238056-scene\/"},{"text":" ","type":"text"},{"type":"text","text":"method of your application scene delegate. It should be invoked for the proper processing of Joyned related content."}],"title":"scene(_:continue:)","kind":"symbol"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK/scene(_:willConnectTo:options:)":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/scene(_:willConnectTo:options:)","navigatorTitle":[{"text":"scene:willConnectTo:options:","kind":"identifier"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdk\/scene(_:willconnectto:options:)","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"scene"},{"kind":"text","text":"("},{"text":"UIScene","preciseIdentifier":"c:objc(cs)UIScene","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"willConnectTo","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UISceneSession","preciseIdentifier":"c:objc(cs)UISceneSession"},{"kind":"text","text":", "},{"text":"options","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIScene","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScene"},{"text":".","kind":"text"},{"preciseIdentifier":"c:objc(cs)UISceneConnectionOptions","text":"ConnectionOptions","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","abstract":[{"type":"text","text":"Call this method from the "},{"isActive":true,"identifier":"https:\/\/developer.apple.com\/documentation\/uikit\/uiscenedelegate\/3197914-scene\/","type":"reference"},{"text":" ","type":"text"},{"type":"text","text":"method of your application scene delegate. It should be invoked for the proper processing of Joyned related content."}],"title":"scene(_:willConnectTo:options:)","kind":"symbol"},"https://developer.apple.com/documentation/uikit/uiscenedelegate/3238056-scene/":{"type":"link","url":"https:\/\/developer.apple.com\/documentation\/uikit\/uiscenedelegate\/3238056-scene\/","title":"UISceneDelegate.scene(_:continue:)","identifier":"https:\/\/developer.apple.com\/documentation\/uikit\/uiscenedelegate\/3238056-scene\/","titleInlineContent":[{"type":"codeVoice","code":"UISceneDelegate.scene(_:continue:)"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/_03_invitation-links":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/_03_invitation-links","url":"\/documentation\/joynedmobilesdk\/_03_invitation-links","role":"article","type":"topic","abstract":[{"type":"text","text":"Handle supported deeplinks for Joyned content"}],"title":"Joyned Session invitation links","kind":"article"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/GettingStarted":{"title":"Getting Started with Joyned mobile SDK","abstract":[],"type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","role":"collectionGroup","url":"\/documentation\/joynedmobilesdk\/gettingstarted","kind":"article"},"https://developer.apple.com/documentation/uikit/uiscenedelegate/3197914-scene/":{"title":"UISceneDelegate.scene(_:willConnectTo:options:)","titleInlineContent":[{"type":"codeVoice","code":"UISceneDelegate.scene(_:willConnectTo:options:)"}],"identifier":"https:\/\/developer.apple.com\/documentation\/uikit\/uiscenedelegate\/3197914-scene\/","url":"https:\/\/developer.apple.com\/documentation\/uikit\/uiscenedelegate\/3197914-scene\/","type":"link"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"scene:openURLContexts:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"+ "},{"text":"scene:openURLContexts:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":[{"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/scene(_:continue:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/scene(_:willConnectTo:options:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/_03_invitation-links"],"generated":true,"title":"SDK - invitation links"}],"op":"replace","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"text":"scene:","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIScene","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScene"},{"kind":"text","text":" *) "},{"text":"scene","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"openURLContexts:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSSet","text":"NSSet<UIOpenURLContext *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"URLContexts","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK\/title","value":"JoynedSDK"},{"op":"replace","value":[{"kind":"identifier","text":"JoynedSDK"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1scene(_:openURLContexts:)\/title","value":"scene:openURLContexts:"},{"value":[{"kind":"text","text":"+ "},{"text":"scene:openURLContexts:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1scene(_:openURLContexts:)\/fragments"},{"value":"scene:continue:","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1scene(_:continue:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1scene(_:continue:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"scene:continue:"}]},{"op":"replace","value":"scene:willConnectTo:options:","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1scene(_:willConnectTo:options:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"scene:willConnectTo:options:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1scene(_:willConnectTo:options:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}