{"metadata":{"navigatorTitle":[{"text":"scene:willConnectTo:options:","kind":"identifier"}],"externalID":"c:@M@JoynedMobileSDK@objc(cs)JoynedSDK(cm)scene:willConnectTo:options:","modules":[{"name":"JoynedMobileSDK"}],"roleHeading":"Type Method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scene","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIScene","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScene"},{"text":", ","kind":"text"},{"text":"willConnectTo","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UISceneSession","preciseIdentifier":"c:objc(cs)UISceneSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"text":"UIScene","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScene"},{"text":".","kind":"text"},{"text":"ConnectionOptions","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISceneConnectionOptions"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"symbolKind":"method","role":"symbol","title":"scene(_:willConnectTo:options:)"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@discardableResult","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scene"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"scene"},{"text":": ","kind":"text"},{"text":"UIScene","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScene"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"willConnectTo"},{"kind":"text","text":" "},{"kind":"internalParam","text":"session"},{"text":": ","kind":"text"},{"text":"UISceneSession","preciseIdentifier":"c:objc(cs)UISceneSession","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"options","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"connectionOptions"},{"text":": ","kind":"text"},{"text":"UIScene","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScene"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"ConnectionOptions","preciseIdentifier":"c:objc(cs)UISceneConnectionOptions"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The scene object being connected to your app.","type":"text"}],"type":"paragraph"}],"name":"scene"},{"name":"session","content":[{"inlineContent":[{"type":"text","text":"The session object containing details about the scene’s configuration."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Additional options for configuring the scene."},{"text":" ","type":"text"},{"text":"Use the information in this object to handle actions that caused the creation of the scene, for example, to respond to a quick action selected by the user.","type":"text"}]}],"name":"connectionOptions"}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"true if the connectionOptions payload contains Joyned related code, otherwise false"}]}]},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"code":["Note: This method handles the case where a deeplink launches the host application"],"type":"codeListing","syntax":null}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/scene(_:willConnectTo:options:)"},"abstract":[{"text":"Call this method from the ","type":"text"},{"identifier":"https:\/\/developer.apple.com\/documentation\/uikit\/uiscenedelegate\/3197914-scene\/","isActive":true,"type":"reference"},{"text":" ","type":"text"},{"type":"text","text":"method of your application scene delegate. It should be invoked for the proper processing of Joyned related content."}],"seeAlsoSections":[{"generated":true,"title":"SDK - invitation links","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/scene(_:continue:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/scene(_:openURLContexts:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/invitation_links"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/joynedmobilesdk\/joynedsdk\/scene(_:willconnectto:options:)"]},{"paths":["\/documentation\/joynedmobilesdk\/joynedsdk\/scene(_:willconnectto:options:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"references":{"https://developer.apple.com/documentation/uikit/uiscenedelegate/3238059-scene/":{"url":"https:\/\/developer.apple.com\/documentation\/uikit\/uiscenedelegate\/3238059-scene\/","type":"link","titleInlineContent":[{"code":"UISceneDelegate.scene(_:openURLContexts:)","type":"codeVoice"}],"identifier":"https:\/\/developer.apple.com\/documentation\/uikit\/uiscenedelegate\/3238059-scene\/","title":"UISceneDelegate.scene(_:openURLContexts:)"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK":{"type":"topic","abstract":[{"type":"text","text":"The main public access class to ther Joyned mobile SDK, use it to interact with the system"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JoynedSDK"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK","navigatorTitle":[{"text":"JoynedSDK","kind":"identifier"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdk","kind":"symbol","role":"symbol","title":"JoynedSDK"},"https://developer.apple.com/documentation/uikit/uiscenedelegate/3238056-scene/":{"identifier":"https:\/\/developer.apple.com\/documentation\/uikit\/uiscenedelegate\/3238056-scene\/","title":"UISceneDelegate.scene(_:continue:)","type":"link","url":"https:\/\/developer.apple.com\/documentation\/uikit\/uiscenedelegate\/3238056-scene\/","titleInlineContent":[{"code":"UISceneDelegate.scene(_:continue:)","type":"codeVoice"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK/scene(_:willConnectTo:options:)":{"abstract":[{"text":"Call this method from the ","type":"text"},{"identifier":"https:\/\/developer.apple.com\/documentation\/uikit\/uiscenedelegate\/3197914-scene\/","isActive":true,"type":"reference"},{"text":" ","type":"text"},{"type":"text","text":"method of your application scene delegate. It should be invoked for the proper processing of Joyned related content."}],"title":"scene(_:willConnectTo:options:)","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"scene","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScene","text":"UIScene"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"willConnectTo"},{"text":": ","kind":"text"},{"text":"UISceneSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISceneSession"},{"text":", ","kind":"text"},{"text":"options","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIScene","kind":"typeIdentifier","text":"UIScene"},{"kind":"text","text":"."},{"preciseIdentifier":"c:objc(cs)UISceneConnectionOptions","text":"ConnectionOptions","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"scene:willConnectTo:options:"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdk\/scene(_:willconnectto:options:)","kind":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/scene(_:willConnectTo:options:)"},"https://developer.apple.com/documentation/uikit/uiscenedelegate/3197914-scene/":{"identifier":"https:\/\/developer.apple.com\/documentation\/uikit\/uiscenedelegate\/3197914-scene\/","title":"UISceneDelegate.scene(_:willConnectTo:options:)","type":"link","url":"https:\/\/developer.apple.com\/documentation\/uikit\/uiscenedelegate\/3197914-scene\/","titleInlineContent":[{"code":"UISceneDelegate.scene(_:willConnectTo:options:)","type":"codeVoice"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/invitation_links":{"abstract":[{"text":"Handle supported deeplinks for Joyned content","type":"text"}],"title":"Joyned Session invitation links","role":"article","type":"topic","url":"\/documentation\/joynedmobilesdk\/invitation_links","kind":"article","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/invitation_links"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK/scene(_:continue:)":{"abstract":[{"text":"Call this method from the ","type":"text"},{"identifier":"https:\/\/developer.apple.com\/documentation\/uikit\/uiscenedelegate\/3238056-scene\/","isActive":true,"type":"reference"},{"text":" ","type":"text"},{"type":"text","text":"method of your application scene delegate. It should be invoked for the proper processing of Joyned related content."}],"title":"scene(_:continue:)","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"scene","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScene","text":"UIScene"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"continue"},{"text":": ","kind":"text"},{"text":"NSUserActivity","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSUserActivity"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"scene:continue:"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdk\/scene(_:continue:)","kind":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/scene(_:continue:)"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK":{"url":"\/documentation\/joynedmobilesdk","title":"JoynedMobileSDK","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","type":"topic","abstract":[{"text":"We help people book together. With a better booking experience, better business results","type":"text"}],"kind":"symbol","role":"collection"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/GettingStarted":{"url":"\/documentation\/joynedmobilesdk\/gettingstarted","title":"Getting Started with Joyned mobile SDK","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","type":"topic","abstract":[],"kind":"article","role":"collectionGroup"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK/scene(_:openURLContexts:)":{"abstract":[{"text":"Call this method from the ","type":"text"},{"identifier":"https:\/\/developer.apple.com\/documentation\/uikit\/uiscenedelegate\/3238059-scene\/","isActive":true,"type":"reference"},{"text":" ","type":"text"},{"type":"text","text":"method of your application scene delegate. It should be invoked for the proper processing of Joyned related content."}],"title":"scene(_:openURLContexts:)","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"scene","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScene","text":"UIScene"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"openURLContexts"},{"text":": ","kind":"text"},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIOpenURLContext","text":"UIOpenURLContext","kind":"typeIdentifier"},{"kind":"text","text":">) -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"scene:openURLContexts:"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdk\/scene(_:openurlcontexts:)","kind":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/scene(_:openURLContexts:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"scene:willConnectTo:options:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"text":"scene:willConnectTo:options:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":[{"generated":true,"title":"SDK - invitation links","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/scene(_:continue:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/scene(_:openURLContexts:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/invitation_links"]}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"scene:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIScene","kind":"typeIdentifier","text":"UIScene"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"scene"},{"text":" ","kind":"text"},{"text":"willConnectTo:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UISceneSession","kind":"typeIdentifier","text":"UISceneSession"},{"kind":"text","text":" *) "},{"text":"session","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"options:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UISceneConnectionOptions","text":"UISceneConnectionOptions","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"connectionOptions"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK\/title","value":"JoynedSDK"},{"value":[{"text":"JoynedSDK","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK\/fragments"},{"value":"scene:willConnectTo:options:","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1scene(_:willConnectTo:options:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"scene:willConnectTo:options:"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1scene(_:willConnectTo:options:)\/fragments","op":"replace"},{"op":"replace","value":"scene:continue:","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1scene(_:continue:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1scene(_:continue:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"scene:continue:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1scene(_:openURLContexts:)\/title","value":"scene:openURLContexts:","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"scene:openURLContexts:"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1scene(_:openURLContexts:)\/fragments"}]}]}