{"abstract":[{"type":"text","text":"An intervention location allowing to override the locale to be used when presenting SDK content on screen"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate\/mobileSDKLocaleForPresentingContent(given:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"mobileSDKLocaleForPresentingContent","kind":"identifier"},{"kind":"text","text":"("},{"text":"given","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"computedLocale"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"mobileSDKLocaleForPresentingContent","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"given"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"modules":[{"name":"JoynedMobileSDK"}],"role":"symbol","externalID":"c:@M@JoynedMobileSDK@objc(pl)JoynedSDKDelegate(im)mobileSDKLocaleForPresentingContentGiven:","symbolKind":"method","title":"mobileSDKLocaleForPresentingContent(given:)","roleHeading":"Instance Method","navigatorTitle":[{"text":"mobileSDKLocaleForPresentingContentGiven:","kind":"identifier"}]},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/GettingStarted","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/joynedmobilesdk\/joynedsdkdelegate\/mobilesdklocaleforpresentingcontent(given:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/joynedmobilesdk\/joynedsdkdelegate\/mobilesdklocaleforpresentingcontent(given:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDKDelegate":{"title":"JoynedSDKDelegate","url":"\/documentation\/joynedmobilesdk\/joynedsdkdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JoynedSDKDelegate"}],"navigatorTitle":[{"text":"JoynedSDKDelegate","kind":"identifier"}],"abstract":[{"text":"Implement this to recive notifications on major actions taken by the SDK and affect its behavior","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDKDelegate/mobileSDKLocaleForPresentingContent(given:)":{"url":"\/documentation\/joynedmobilesdk\/joynedsdkdelegate\/mobilesdklocaleforpresentingcontent(given:)","title":"mobileSDKLocaleForPresentingContent(given:)","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"mobileSDKLocaleForPresentingContentGiven:"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate\/mobileSDKLocaleForPresentingContent(given:)","abstract":[{"type":"text","text":"An intervention location allowing to override the locale to be used when presenting SDK content on screen"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mobileSDKLocaleForPresentingContent"},{"text":"(","kind":"text"},{"text":"given","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/GettingStarted":{"kind":"article","role":"collection","url":"\/documentation\/gettingstarted","type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/GettingStarted","title":"Getting Started with Joyned mobile SDK","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"mobileSDKLocaleForPresentingContentGiven:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mobileSDKLocaleForPresentingContentGiven:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"mobileSDKLocaleForPresentingContentGiven:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"computedLocale"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDKDelegate\/title","value":"JoynedSDKDelegate"},{"op":"replace","value":[{"text":"JoynedSDKDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDKDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDKDelegate~1mobileSDKLocaleForPresentingContent(given:)\/title","value":"mobileSDKLocaleForPresentingContentGiven:"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDKDelegate~1mobileSDKLocaleForPresentingContent(given:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"mobileSDKLocaleForPresentingContentGiven:","kind":"identifier"}],"op":"replace"}]}]}