{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"mobileSDKDidActivateSuccessfully","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/GettingStarted","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate"]]},"kind":"symbol","abstract":[{"type":"text","text":"Called when the SDK was activated successfully"}],"metadata":{"role":"symbol","required":true,"roleHeading":"Instance Method","externalID":"c:@M@JoynedMobileSDK@objc(pl)JoynedSDKDelegate(im)mobileSDKDidActivateSuccessfully","modules":[{"name":"JoynedMobileSDK"}],"navigatorTitle":[{"kind":"identifier","text":"mobileSDKDidActivateSuccessfully"}],"title":"mobileSDKDidActivateSuccessfully()","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"mobileSDKDidActivateSuccessfully","kind":"identifier"},{"text":"()","kind":"text"}]},"identifier":{"url":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate\/mobileSDKDidActivateSuccessfully()","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/joynedmobilesdk\/joynedsdkdelegate\/mobilesdkdidactivatesuccessfully()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/joynedmobilesdk\/joynedsdkdelegate\/mobilesdkdidactivatesuccessfully()"]}],"sections":[],"references":{"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDKDelegate/mobileSDKDidActivateSuccessfully()":{"url":"\/documentation\/joynedmobilesdk\/joynedsdkdelegate\/mobilesdkdidactivatesuccessfully()","title":"mobileSDKDidActivateSuccessfully()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mobileSDKDidActivateSuccessfully"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"mobileSDKDidActivateSuccessfully","kind":"identifier"}],"abstract":[{"text":"Called when the SDK was activated successfully","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate\/mobileSDKDidActivateSuccessfully()","required":true},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/GettingStarted":{"url":"\/documentation\/gettingstarted","kind":"article","abstract":[],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/GettingStarted","title":"Getting Started with Joyned mobile SDK","role":"collection","type":"topic"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDKDelegate":{"title":"JoynedSDKDelegate","url":"\/documentation\/joynedmobilesdk\/joynedsdkdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JoynedSDKDelegate"}],"navigatorTitle":[{"text":"JoynedSDKDelegate","kind":"identifier"}],"abstract":[{"text":"Implement this to recive notifications on major actions taken by the SDK and affect its behavior","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"mobileSDKDidActivateSuccessfully","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"mobileSDKDidActivateSuccessfully","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"mobileSDKDidActivateSuccessfully","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDKDelegate~1mobileSDKDidActivateSuccessfully()\/title","value":"mobileSDKDidActivateSuccessfully"},{"value":[{"text":"- ","kind":"text"},{"text":"mobileSDKDidActivateSuccessfully","kind":"identifier"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDKDelegate~1mobileSDKDidActivateSuccessfully()\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDKDelegate\/title","value":"JoynedSDKDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDKDelegate\/fragments","value":[{"kind":"identifier","text":"JoynedSDKDelegate"}]}]}]}