{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"Article","modules":[{"name":"JoynedMobileSDK"}],"title":"Joyned Session invitation links","role":"article"},"kind":"article","abstract":[{"type":"text","text":"Handle supported deeplinks for Joyned content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/joynedmobilesdk\/_03_invitation-links"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/joynedmobilesdk\/_03_invitation-links"]}],"hierarchy":{"paths":[["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK"],["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted"],["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK"],["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK"]]},"primaryContentSections":[{"kind":"content","content":[{"level":2,"anchor":"Overview","type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"text":"Joyned invitation links allow a user to invite his friends into his Joyned session.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"The simplest way of doing so is by opening a Joyned session and using its UI to share an invitation via one of the supported share options, this can be done from both the Web UI or the mobile app.","type":"text"}]},{"type":"tabNavigator","tabs":[{"content":[{"numberOfColumns":2,"columns":[{"content":[{"inlineContent":[{"type":"image","identifier":"screenshot_web_invitation_01.png"}],"type":"paragraph"}],"size":1},{"size":1,"content":[{"inlineContent":[{"type":"image","identifier":"screenshot_web_invitation_02.png"}],"type":"paragraph"}]}],"type":"row"}],"title":"Web"},{"title":"Mobile","content":[{"type":"row","numberOfColumns":3,"columns":[{"size":1,"content":[{"type":"paragraph","inlineContent":[{"identifier":"screenshot_mobile_invitation_01.png","type":"image"}]}]},{"content":[{"inlineContent":[{"type":"image","identifier":"screenshot_mobile_invitation_02.png"}],"type":"paragraph"}],"size":1},{"size":1,"content":[{"type":"paragraph","inlineContent":[{"type":"image","identifier":"screenshot_mobile_invitation_03.png"}]}]}]}]}]},{"inlineContent":[{"type":"strong","inlineContent":[{"text":"Share payload:","type":"text"}]}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"The share payload contains a “short” link which will redirect the system to a “long” link.","type":"text"}]},{"inlineContent":[{"text":"The “long” link needs to be of a format supported by the host mobile appliaction for the system integration to fully work.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Example of a share message:"}]}]},{"syntax":null,"code":["I found a good option on JOYNED ","More details in my favorites list","https:\/\/gamitee-demo.joyned.chat\/v3ngpua?sn=clipboard"],"type":"codeListing"},{"inlineContent":[{"type":"text","text":"To integrate the invitation links element into the application you first need to implement Universal links"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Implement Universal links by following the instruction as shown on apple developer website"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"https:\/\/developer.apple.com\/ios\/universal-links\/"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"https:\/\/developer.apple.com\/documentation\/xcode\/allowing-apps-and-websites-to-link-to-your-content","type":"reference"}]}]}]},{"inlineContent":[{"text":"Once implemented, you need to add the relevent Joyned methods from within the applications scene delegate:","type":"text"}],"type":"paragraph"},{"code":["extension SceneDelegate : UISceneDelegate","{","    \/\/ Deeplink or Universial Link Open when app is start.","    func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions)","    {   ","        ...","        JoynedSDK.scene(scene, willConnectTo: session, options: connectionOptions)","        ...","    }","","    \/\/ Deeplink link Open when app is onPause","    func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>) ","    {   ","        ...","        JoynedSDK.scene(scene, openURLContexts: URLContexts)","        ...","    }","    \/\/ Universial link Open when app is onPause","    func scene(_ scene: UIScene, continue userActivity: NSUserActivity)","    {","        ...","        JoynedSDK.scene(scene, continue: userActivity)","        ...","    }","}"],"syntax":"swift","type":"codeListing"},{"type":"heading","text":"For more information see:","anchor":"For-more-information-see","level":4},{"style":"list","type":"links","items":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/scene(_:continue:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/scene(_:openURLContexts:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/scene(_:willConnectTo:options:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/_03_invitation-links"},"references":{"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK":{"title":"JoynedMobileSDK","abstract":[{"text":"We help people book together. With a better booking experience, better business results","type":"text"}],"type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","role":"collection","url":"\/documentation\/joynedmobilesdk","kind":"symbol"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK/scene(_:openURLContexts:)":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/scene(_:openURLContexts:)","navigatorTitle":[{"text":"scene:openURLContexts:","kind":"identifier"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdk\/scene(_:openurlcontexts:)","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"scene"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIScene","text":"UIScene","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"openURLContexts","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"text":"UIOpenURLContext","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIOpenURLContext"},{"text":">) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","abstract":[{"type":"text","text":"Call this method from the "},{"isActive":true,"type":"reference","identifier":"https:\/\/developer.apple.com\/documentation\/uikit\/uiscenedelegate\/3238059-scene\/"},{"type":"text","text":" "},{"type":"text","text":"method of your application scene delegate. It should be invoked for the proper processing of Joyned related content."}],"title":"scene(_:openURLContexts:)","kind":"symbol"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/GettingStarted":{"title":"Getting Started with Joyned mobile SDK","abstract":[],"type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","role":"collectionGroup","url":"\/documentation\/joynedmobilesdk\/gettingstarted","kind":"article"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK/scene(_:continue:)":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/scene(_:continue:)","navigatorTitle":[{"text":"scene:continue:","kind":"identifier"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdk\/scene(_:continue:)","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"scene","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIScene","text":"UIScene","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"continue"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSUserActivity","text":"NSUserActivity","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","abstract":[{"type":"text","text":"Call this method from the "},{"type":"reference","isActive":true,"identifier":"https:\/\/developer.apple.com\/documentation\/uikit\/uiscenedelegate\/3238056-scene\/"},{"text":" ","type":"text"},{"type":"text","text":"method of your application scene delegate. It should be invoked for the proper processing of Joyned related content."}],"title":"scene(_:continue:)","kind":"symbol"},"screenshot_mobile_invitation_01.png":{"type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/screenshot_mobile_invitation_01.png"}],"alt":"Joyned invitation mobile example 01","identifier":"screenshot_mobile_invitation_01.png"},"screenshot_web_invitation_02.png":{"identifier":"screenshot_web_invitation_02.png","type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/screenshot_web_invitation_02.png"}],"alt":"Joyned invitation web example 02"},"https://developer.apple.com/documentation/uikit/uiscenedelegate/3197914-scene/":{"title":"UISceneDelegate.scene(_:willConnectTo:options:)","url":"https:\/\/developer.apple.com\/documentation\/uikit\/uiscenedelegate\/3197914-scene\/","identifier":"https:\/\/developer.apple.com\/documentation\/uikit\/uiscenedelegate\/3197914-scene\/","type":"link","titleInlineContent":[{"code":"UISceneDelegate.scene(_:willConnectTo:options:)","type":"codeVoice"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK":{"title":"JoynedSDK","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The main public access class to ther Joyned mobile SDK, use it to interact with the system"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdk","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JoynedSDK"}],"navigatorTitle":[{"text":"JoynedSDK","kind":"identifier"}]},"screenshot_mobile_invitation_02.png":{"type":"image","variants":[{"url":"\/images\/screenshot_mobile_invitation_02.png","traits":["1x","light"]}],"alt":"Joyned invitation mobile example 02","identifier":"screenshot_mobile_invitation_02.png"},"screenshot_web_invitation_01.png":{"type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/screenshot_web_invitation_01.png"}],"identifier":"screenshot_web_invitation_01.png","alt":"Joyned invitation web example 01"},"https://developer.apple.com/documentation/uikit/uiscenedelegate/3238059-scene/":{"url":"https:\/\/developer.apple.com\/documentation\/uikit\/uiscenedelegate\/3238059-scene\/","type":"link","titleInlineContent":[{"type":"codeVoice","code":"UISceneDelegate.scene(_:openURLContexts:)"}],"title":"UISceneDelegate.scene(_:openURLContexts:)","identifier":"https:\/\/developer.apple.com\/documentation\/uikit\/uiscenedelegate\/3238059-scene\/"},"https://developer.apple.com/ios/universal-links/":{"title":"universal-links -  general","type":"link","titleInlineContent":[{"type":"text","text":"universal-links -  general"}],"identifier":"https:\/\/developer.apple.com\/ios\/universal-links\/","url":"https:\/\/developer.apple.com\/ios\/universal-links\/"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK/scene(_:willConnectTo:options:)":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/scene(_:willConnectTo:options:)","navigatorTitle":[{"text":"scene:willConnectTo:options:","kind":"identifier"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdk\/scene(_:willconnectto:options:)","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"scene"},{"kind":"text","text":"("},{"text":"UIScene","preciseIdentifier":"c:objc(cs)UIScene","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"willConnectTo","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UISceneSession","preciseIdentifier":"c:objc(cs)UISceneSession"},{"kind":"text","text":", "},{"text":"options","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIScene","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScene"},{"text":".","kind":"text"},{"preciseIdentifier":"c:objc(cs)UISceneConnectionOptions","text":"ConnectionOptions","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","abstract":[{"type":"text","text":"Call this method from the "},{"isActive":true,"identifier":"https:\/\/developer.apple.com\/documentation\/uikit\/uiscenedelegate\/3197914-scene\/","type":"reference"},{"text":" ","type":"text"},{"type":"text","text":"method of your application scene delegate. It should be invoked for the proper processing of Joyned related content."}],"title":"scene(_:willConnectTo:options:)","kind":"symbol"},"https://developer.apple.com/documentation/xcode/allowing-apps-and-websites-to-link-to-your-content":{"url":"https:\/\/developer.apple.com\/documentation\/xcode\/allowing-apps-and-websites-to-link-to-your-content","type":"link","titleInlineContent":[{"type":"text","text":"universal-links - allowing apps to link to your content"}],"title":"universal-links - allowing apps to link to your content","identifier":"https:\/\/developer.apple.com\/documentation\/xcode\/allowing-apps-and-websites-to-link-to-your-content"},"https://developer.apple.com/documentation/uikit/uiscenedelegate/3238056-scene/":{"title":"UISceneDelegate.scene(_:continue:)","type":"link","titleInlineContent":[{"type":"codeVoice","code":"UISceneDelegate.scene(_:continue:)"}],"identifier":"https:\/\/developer.apple.com\/documentation\/uikit\/uiscenedelegate\/3238056-scene\/","url":"https:\/\/developer.apple.com\/documentation\/uikit\/uiscenedelegate\/3238056-scene\/"},"screenshot_mobile_invitation_03.png":{"type":"image","variants":[{"url":"\/images\/screenshot_mobile_invitation_03.png","traits":["1x","light"]}],"alt":"Joyned invitation mobile example 03","identifier":"screenshot_mobile_invitation_03.png"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1scene(_:openURLContexts:)\/title","value":"scene:openURLContexts:","op":"replace"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1scene(_:openURLContexts:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"scene:openURLContexts:"}],"op":"replace"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1scene(_:continue:)\/title","value":"scene:continue:","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"scene:continue:","kind":"identifier"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1scene(_:continue:)\/fragments","op":"replace"},{"op":"replace","value":"JoynedSDK","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK\/title"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK\/fragments","value":[{"text":"JoynedSDK","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1scene(_:willConnectTo:options:)\/title","value":"scene:willConnectTo:options:"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1scene(_:willConnectTo:options:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"scene:willConnectTo:options:","kind":"identifier"}]}]}]}