{"hierarchy":{"paths":[["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/GettingStarted"],["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/GettingStarted","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK"]]},"sections":[],"seeAlsoSections":[{"title":"Essentials","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/installation","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/activation","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/screen_llst","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate"],"generated":true}],"abstract":[{"type":"text","text":"Joyned mobile SDK provides several intervention hooks via the "},{"type":"reference","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate","isActive":true},{"type":"text","text":" protocol"}],"kind":"article","primaryContentSections":[{"content":[{"type":"heading","level":2,"anchor":"Overview","text":"Overview"},{"inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"JoynedSDKDelegate"},{"text":" is responsible for global interactions with the SDK, things like what locale the system should use, or simple notification on some system events","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"inlineContent":[{"text":"Notifications:","type":"text"}],"type":"strong"}]},{"type":"links","items":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate\/mobileSDKDidActivateSuccessfully()","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate\/mobileSDKDidFailToActivate()"],"style":"list"},{"type":"paragraph","inlineContent":[{"inlineContent":[{"type":"text","text":"Locale"}],"type":"strong"}]},{"type":"links","style":"list","items":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate\/mobileSDKLocaleForPresentingContent(given:)"]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Navigation actions"}]}]},{"items":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate\/mobileSDKDidTriggerNavigation(for:)"],"style":"list","type":"links"},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"text":"Please note:","type":"text"}]}]},{"inlineContent":[{"type":"emphasis","inlineContent":[{"text":"You will not be able to interact with JoynedMobileSDK without implementing this protocol.","type":"text"}]}],"type":"paragraph"},{"code":["@objc(JoynedSDKDelegate)","public protocol JoynedSDKDelegate : NSObjectProtocol","{","    \/\/\/ Called when the SDK was activated successfully","    @objc optional func mobileSDKDidActivateSuccessfully()","    ","    \/\/\/ Called when the SDK failed to activate","    @objc optional func mobileSDKDidFailToActivate()","    ","    \/\/\/ An intervention location allowing to override the locale to be used when presenting SDK content on screen","    @objc optional func mobileSDKLocaleWhenPresentingContent(given computedLocale: String) -> String","    ","    \/\/\/ Called when a user clicks on an offering within the Joyned UI","    @objc func mobileSDKDidTriggerNavigation(for navigationPayload: JoynedNavigationProtocol)","}"],"type":"codeListing","syntax":"swift"},{"inlineContent":[{"inlineContent":[{"type":"text","text":"Usage Example:"}],"type":"strong"}],"type":"paragraph"},{"syntax":"swift","code":["import JoynedMobileSDK","extension AppDelegate : JoynedSDKDelegate","{","    func mobileSDKDidActivateSuccessfully()","    {","        print(\"Called mobileSDKDidActivateSuccessfullyl\")","    }","    func mobileSDKDidFailToActivate()","    {","        print(\"Called mobileSDKDidFailToActivate\")","    }","    func mobileSDKLocaleWhenPresentingContent(given computedLocale: String) -> String ","    {","        print(\"Called mobileSDKLocaleWhenPresentingContent(given:)\")","        return computedLocale.replacingOccurrences(of: \"_\", with: \"-\")","    }","    func mobileSDKDidTriggerNavigation(for navigationPayload: JoynedNavigationProtocol)","    {","        print(\"Called mobileSDKDidTriggerNavigation(for:)\")","        \/\/ Dd in-app navigation","    }","}"],"type":"codeListing"}],"kind":"content"}],"metadata":{"roleHeading":"Article","modules":[{"name":"JoynedMobileSDK"}],"title":"Global Delegate","role":"article"},"identifier":{"url":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/global_delegate","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDKDelegate/mobileSDKLocaleForPresentingContent(given:)":{"url":"\/documentation\/joynedmobilesdk\/joynedsdkdelegate\/mobilesdklocaleforpresentingcontent(given:)","title":"mobileSDKLocaleForPresentingContent(given:)","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"mobileSDKLocaleForPresentingContentGiven:"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate\/mobileSDKLocaleForPresentingContent(given:)","abstract":[{"type":"text","text":"An intervention location allowing to override the locale to be used when presenting SDK content on screen"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mobileSDKLocaleForPresentingContent"},{"text":"(","kind":"text"},{"text":"given","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK":{"kind":"symbol","type":"topic","url":"\/documentation\/joynedmobilesdk\/joynedsdk","abstract":[{"text":"The main public access class to ther Joyned mobile SDK, use it to interact with the system","type":"text"}],"title":"JoynedSDK","role":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JoynedSDK"}],"navigatorTitle":[{"text":"JoynedSDK","kind":"identifier"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDKDelegate/mobileSDKDidActivateSuccessfully()":{"url":"\/documentation\/joynedmobilesdk\/joynedsdkdelegate\/mobilesdkdidactivatesuccessfully()","title":"mobileSDKDidActivateSuccessfully()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mobileSDKDidActivateSuccessfully"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"mobileSDKDidActivateSuccessfully","kind":"identifier"}],"abstract":[{"text":"Called when the SDK was activated successfully","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate\/mobileSDKDidActivateSuccessfully()","required":true},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDKDelegate":{"title":"JoynedSDKDelegate","url":"\/documentation\/joynedmobilesdk\/joynedsdkdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JoynedSDKDelegate"}],"navigatorTitle":[{"text":"JoynedSDKDelegate","kind":"identifier"}],"abstract":[{"text":"Implement this to recive notifications on major actions taken by the SDK and affect its behavior","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDKDelegate/mobileSDKDidTriggerNavigation(for:)":{"required":true,"url":"\/documentation\/joynedmobilesdk\/joynedsdkdelegate\/mobilesdkdidtriggernavigation(for:)","title":"mobileSDKDidTriggerNavigation(for:)","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"mobileSDKDidTriggerNavigationFor:"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate\/mobileSDKDidTriggerNavigation(for:)","abstract":[{"type":"text","text":"Called when a user clicks on an offering within the Joyned UI, use this as a trigger for in-app navigation, for navigation details lokk into the payload object"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mobileSDKDidTriggerNavigation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JoynedMobileSDK@objc(cs)JoynedOfferingResponse","text":"JoynedOfferingResponse"},{"kind":"text","text":")"}],"type":"topic"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDKDelegate/mobileSDKDidFailToActivate()":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"mobileSDKDidFailToActivate"},{"text":"()","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate\/mobileSDKDidFailToActivate()","type":"topic","abstract":[{"text":"Called when the SDK failed to activate","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"mobileSDKDidFailToActivate","kind":"identifier"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdkdelegate\/mobilesdkdidfailtoactivate()","title":"mobileSDKDidFailToActivate()"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/GettingStarted":{"kind":"article","role":"collection","url":"\/documentation\/gettingstarted","type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/GettingStarted","title":"Getting Started with Joyned mobile SDK","abstract":[]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/installation":{"url":"\/documentation\/joynedmobilesdk\/installation","title":"Library installation","kind":"article","role":"article","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/installation","abstract":[{"type":"text","text":"How to install this library"}],"type":"topic"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/screen_llst":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/screen_llst","type":"topic","kind":"article","title":"Screen Validation Controls","role":"article","abstract":[{"type":"text","text":"Joyned Mobile SDK screen change monitor"}],"url":"\/documentation\/joynedmobilesdk\/screen_llst"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/activation":{"url":"\/documentation\/joynedmobilesdk\/activation","title":"Activation Methods","kind":"article","role":"article","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/activation","abstract":[{"type":"text","text":"There are several different ways to activate of the Joyned mobile SDK"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDKDelegate~1mobileSDKLocaleForPresentingContent(given:)\/title","value":"mobileSDKLocaleForPresentingContentGiven:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"mobileSDKLocaleForPresentingContentGiven:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDKDelegate~1mobileSDKLocaleForPresentingContent(given:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK\/title","value":"JoynedSDK"},{"value":[{"text":"JoynedSDK","kind":"identifier"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK\/fragments","op":"replace"},{"op":"replace","value":"mobileSDKDidActivateSuccessfully","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDKDelegate~1mobileSDKDidActivateSuccessfully()\/title"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDKDelegate~1mobileSDKDidActivateSuccessfully()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"mobileSDKDidActivateSuccessfully","kind":"identifier"}]},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDKDelegate\/title","value":"JoynedSDKDelegate","op":"replace"},{"value":[{"text":"JoynedSDKDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDKDelegate\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDKDelegate~1mobileSDKDidTriggerNavigation(for:)\/title","value":"mobileSDKDidTriggerNavigationFor:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDKDelegate~1mobileSDKDidTriggerNavigation(for:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"mobileSDKDidTriggerNavigationFor:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDKDelegate~1mobileSDKDidFailToActivate()\/title","value":"mobileSDKDidFailToActivate"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDKDelegate~1mobileSDKDidFailToActivate()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mobileSDKDidFailToActivate"}]}]}]}