{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"Hosted UI","modules":[{"name":"JoynedMobileSDK"}],"roleHeading":"Article","role":"article"},"abstract":[{"text":"Hosted Joyned UI","type":"text"},{"text":" ","type":"text"},{"text":"Joyned mobile SDK provides a few views which are ment to be used within application that hosts the SDK","type":"text"}],"seeAlsoSections":[{"title":"Hosted Joyned UI","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate"],"generated":true}],"sections":[],"primaryContentSections":[{"content":[{"level":2,"text":"Overview","type":"heading","anchor":"Overview"},{"inlineContent":[{"text":"There are two ways to integrated Joyned mobile SDK views into the host application:","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"via Xib\/Storyboard"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"via Code"}],"type":"paragraph"}]}],"type":"unorderedList"},{"type":"heading","anchor":"XibStoryboard","level":3,"text":"Xib\/Storyboard"},{"type":"paragraph","inlineContent":[{"text":"To integrate a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton"},{"type":"text","text":" in to Xib or Storyboard based UI all you need to do is to add a view element to the Xib\/Storyboard document and set its custom class to "},{"isActive":true,"type":"reference","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton"},{"text":".","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Make sure to also set the "},{"type":"codeVoice","code":"module"},{"text":" value in the inspector to ","type":"text"},{"type":"codeVoice","code":"JoynedMobileSDK"}]},{"type":"paragraph","inlineContent":[{"identifier":"screenshot_joyned_button.png","type":"image"}]},{"anchor":"Code-Integration","type":"heading","level":3,"text":"Code Integration"},{"type":"paragraph","inlineContent":[{"text":"To integrate a ","type":"text"},{"isActive":true,"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton","type":"reference"},{"type":"text","text":" in to a UIKit code based UI, use the following code:"}]},{"code":["lass ExampleViewController : UIViewController","{","    \/\/ MARK: - type - enum","    ","    \/\/ MARK: - Properties","    internal var venue : Venue!","","    \/\/ MARK: - View LifeCycle","    override func viewDidLoad()","    {","        super.viewDidLoad()","","","        let button = JoynedSDK.generateJoynedButton(frame: CGRect(x: 100, y: 500, width: 70, height: 34), with: self)","        view.addSubview(button)","    }","}"],"type":"codeListing","syntax":"swift"},{"inlineContent":[{"inlineContent":[{"type":"text","text":"Also see"}],"type":"strong"},{"type":"text","text":":"}],"type":"paragraph"},{"type":"links","style":"list","items":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/generateJoynedButton(frame:with:)"]},{"type":"paragraph","inlineContent":[{"text":"Make sure that you implement the button’s delegate protocol and set it’s delegate like so:","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["extension ExampleViewController : JoynedButtonDelegate","{","    func willPresentMobileSDKContent()","    {","        logger.debug()","    }","    ","    func joynedButton(_ button: JoynedButton, productOfferingFor location: CGPoint) -> JoynedNavigationRequestProtocol?","    {","        logger.debug()","        ","        return encode(product: venue)","    }","    ","    private func encode(product item: Venue?) -> JoynedNavigationRequestProtocol?","    {","        guard let venue   = item              else { return nil }","        guard let product = venue.toPayload() else { return nil }","        guard let extra   = venue.toJSON()    else { return nil }","        return JoynedNavigationRequest(offeringString: product, extraString: extra)","    }","}"]},{"type":"heading","anchor":"For-more-information-see","text":"For more information see:","level":4},{"style":"list","items":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate"],"type":"links"}],"kind":"content"}],"identifier":{"url":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/hosted_ui","interfaceLanguage":"swift"},"kind":"article","hierarchy":{"paths":[["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/GettingStarted"],["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/GettingStarted","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK"]]},"references":{"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK/generateJoynedButton(frame:with:)":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/generateJoynedButton(frame:with:)","type":"topic","kind":"symbol","title":"generateJoynedButton(frame:with:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"generateJoynedButtonWithFrame:with:"}],"abstract":[{"text":"Use this method to generate a new instance of ","type":"text"},{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton","isActive":true,"type":"reference"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdk\/generatejoynedbutton(frame:with:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"generateJoynedButton","kind":"identifier"},{"text":"(","kind":"text"},{"text":"frame","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"JoynedButtonDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@JoynedMobileSDK@objc(pl)JoynedButtonDelegate"},{"text":"?) -> ","kind":"text"},{"text":"JoynedButton","kind":"typeIdentifier","preciseIdentifier":"c:@M@JoynedMobileSDK@objc(cs)JoynedButton"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButtonDelegate":{"title":"JoynedButtonDelegate","url":"\/documentation\/joynedmobilesdk\/joynedbuttondelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"JoynedButtonDelegate","kind":"identifier"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"JoynedButtonDelegate","kind":"identifier"}],"abstract":[]},"screenshot_joyned_button.png":{"identifier":"screenshot_joyned_button.png","type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/screenshot_joyned_button.png"}],"alt":"Joyned button example"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/GettingStarted":{"kind":"article","role":"collection","url":"\/documentation\/gettingstarted","type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/GettingStarted","title":"Getting Started with Joyned mobile SDK","abstract":[]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JoynedButton"}],"role":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedbutton","type":"topic","navigatorTitle":[{"text":"JoynedButton","kind":"identifier"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton","title":"JoynedButton","abstract":[]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK":{"kind":"symbol","type":"topic","url":"\/documentation\/joynedmobilesdk\/joynedsdk","abstract":[{"text":"The main public access class to ther Joyned mobile SDK, use it to interact with the system","type":"text"}],"title":"JoynedSDK","role":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JoynedSDK"}],"navigatorTitle":[{"text":"JoynedSDK","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1generateJoynedButton(frame:with:)\/title","value":"generateJoynedButtonWithFrame:with:","op":"replace"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1generateJoynedButton(frame:with:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"generateJoynedButtonWithFrame:with:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButtonDelegate\/title","op":"replace","value":"JoynedButtonDelegate"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButtonDelegate\/fragments","value":[{"kind":"identifier","text":"JoynedButtonDelegate"}]},{"value":"JoynedButton","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton\/title"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton\/fragments","value":[{"text":"JoynedButton","kind":"identifier"}]},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK\/title","value":"JoynedSDK","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK\/fragments","value":[{"text":"JoynedSDK","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}