{"variants":[{"paths":["\/documentation\/joynedmobilesdk\/joynedofferingresponse"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/joynedmobilesdk\/joynedofferingresponse"]}],"sections":[],"metadata":{"modules":[{"name":"JoynedMobileSDK"}],"roleHeading":"Class","role":"symbol","navigatorTitle":[{"text":"JoynedOfferingResponse","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JoynedOfferingResponse","kind":"identifier"}],"symbolKind":"class","title":"JoynedOfferingResponse","externalID":"c:@M@JoynedMobileSDK@objc(cs)JoynedOfferingResponse"},"identifier":{"url":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingResponse","interfaceLanguage":"swift"},"topicSections":[{"title":"Representation","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingResponse\/originalOffering","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingResponse\/extraAppContent"]},{"title":"JSON Representation","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingResponse\/originalOfferingJSON","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingResponse\/extraAppContentJSON"]},{"title":"Convenience accessors","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingResponse\/directUrl"]}],"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(pl)NSObject","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/s7CVarArgP","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/s28CustomDebugStringConvertibleP","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/s23CustomStringConvertibleP","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/SQ","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/SH"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/offering","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingRequest"],"title":"Offering Related API"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(JoynedOfferingResponse) "},{"kind":"attribute","text":"@objcMembers"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JoynedOfferingResponse"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/GettingStarted"]]},"references":{"doc://co.joyned.mobile.JoynedMobileSDK/@M@JoynedMobileSDK@objc(cs)_JoynedOfferingData":{"type":"unresolvable","title":"_JoynedOfferingData","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/@M@JoynedMobileSDK@objc(cs)_JoynedOfferingData"},"doc://co.joyned.mobile.JoynedMobileSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(pl)NSObject"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedOfferingResponse/directUrl":{"abstract":[{"text":"The offering direct URL as contained in the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingResponse\/originalOffering"},{"text":" dictionary","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"directUrl","kind":"identifier"}],"title":"directUrl","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingResponse\/directUrl","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"directUrl","kind":"identifier"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?","kind":"text"}],"kind":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedofferingresponse\/directurl"},"doc://co.joyned.mobile.JoynedMobileSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/SQ"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedOfferingResponse/originalOfferingJSON":{"url":"\/documentation\/joynedmobilesdk\/joynedofferingresponse\/originalofferingjson","abstract":[{"type":"text","text":"A JSON string representation of the offering original content payload"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"originalOfferingJSON","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"originalOfferingJSON"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingResponse\/originalOfferingJSON","title":"originalOfferingJSON"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedOfferingResponse/extraAppContent":{"url":"\/documentation\/joynedmobilesdk\/joynedofferingresponse\/extraappcontent","abstract":[{"text":"A dictionary containing the extra appliction data, may be used for in-app navigation logic","type":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"extraAppContent","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"extraAppContent"},{"kind":"text","text":": "},{"text":"NSDictionary","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary"}],"kind":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingResponse\/extraAppContent","title":"extraAppContent"},"doc://co.joyned.mobile.JoynedMobileSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/s23CustomStringConvertibleP"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/offering":{"title":"Offering handling API","url":"\/documentation\/joynedmobilesdk\/offering","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/offering","kind":"article","type":"topic","role":"article","abstract":[{"text":"API for interacting with JoynedMobileSDK offerings","type":"text"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedOfferingRequest":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"JoynedOfferingRequest","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"JoynedOfferingRequest","kind":"identifier"}],"role":"symbol","abstract":[],"url":"\/documentation\/joynedmobilesdk\/joynedofferingrequest","type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingRequest","title":"JoynedOfferingRequest"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedOfferingResponse":{"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"text":"JoynedOfferingResponse","kind":"identifier"}],"title":"JoynedOfferingResponse","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingResponse","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"JoynedOfferingResponse","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedofferingresponse"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/GettingStarted":{"kind":"article","role":"collection","url":"\/documentation\/gettingstarted","type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/GettingStarted","title":"Getting Started with Joyned mobile SDK","abstract":[]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedOfferingResponse/extraAppContentJSON":{"url":"\/documentation\/joynedmobilesdk\/joynedofferingresponse\/extraappcontentjson","abstract":[{"type":"text","text":"A JSON string representation of the offering extra application content payload"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"extraAppContentJSON"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"extraAppContentJSON"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingResponse\/extraAppContentJSON","title":"extraAppContentJSON"},"doc://co.joyned.mobile.JoynedMobileSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://co.joyned.mobile.JoynedMobileSDK/SH":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://co.joyned.mobile.JoynedMobileSDK/s7CVarArgP":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedOfferingResponse/originalOffering":{"abstract":[{"text":"A dictionary containing the original offering data","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"originalOffering","kind":"identifier"}],"title":"originalOffering","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingResponse\/originalOffering","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"originalOffering","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedofferingresponse\/originaloffering"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"JoynedOfferingResponse"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"JoynedOfferingResponse","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"JoynedOfferingResponse"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingResponse\/originalOffering","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingResponse\/extraAppContent"],"title":"Representation"},{"title":"JSON Representation","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingResponse\/originalOfferingJSON","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingResponse\/extraAppContentJSON"]},{"title":"Convenience accessors","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingResponse\/directUrl"]}]},{"op":"replace","value":[{"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/@M@JoynedMobileSDK@objc(cs)_JoynedOfferingData"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}],"path":"\/relationshipsSections"},{"op":"replace","value":[{"generated":true,"title":"Offering Related API","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingRequest"]}],"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JoynedOfferingResponse","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"_JoynedOfferingData","kind":"typeIdentifier","preciseIdentifier":"c:@M@JoynedMobileSDK@objc(cs)_JoynedOfferingData"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"directUrl","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingResponse~1directUrl\/title"},{"value":[{"text":"directUrl","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingResponse~1directUrl\/fragments"},{"value":"originalOfferingJSON","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingResponse~1originalOfferingJSON\/title"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingResponse~1originalOfferingJSON\/fragments","value":[{"kind":"identifier","text":"originalOfferingJSON"}]},{"value":"extraAppContent","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingResponse~1extraAppContent\/title"},{"value":[{"kind":"identifier","text":"extraAppContent"}],"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingResponse~1extraAppContent\/fragments"},{"op":"replace","value":"JoynedOfferingRequest","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingRequest\/title"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingRequest\/fragments","op":"replace","value":[{"kind":"identifier","text":"JoynedOfferingRequest"}]},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingResponse\/title","value":"JoynedOfferingResponse","op":"replace"},{"value":[{"text":"JoynedOfferingResponse","kind":"identifier"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingResponse\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingResponse~1extraAppContentJSON\/title","value":"extraAppContentJSON"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingResponse~1extraAppContentJSON\/fragments","value":[{"kind":"identifier","text":"extraAppContentJSON"}],"op":"replace"},{"value":"originalOffering","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingResponse~1originalOffering\/title"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingResponse~1originalOffering\/fragments","value":[{"kind":"identifier","text":"originalOffering"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}