{"kind":"symbol","seeAlsoSections":[{"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/hosted_ui","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate"],"generated":true,"title":"Hosted Joyned UI"}],"metadata":{"role":"symbol","roleHeading":"Class","title":"JoynedButton","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JoynedButton"}],"modules":[{"name":"JoynedMobileSDK"}],"externalID":"c:@M@JoynedMobileSDK@objc(cs)JoynedButton","navigatorTitle":[{"kind":"identifier","text":"JoynedButton"}],"symbolKind":"class"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton"},"hierarchy":{"paths":[["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/GettingStarted"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"topicSections":[{"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/init(frame:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/init(coder:)"],"title":"Creating a Joyned Button"},{"title":"Delegations","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/delegate","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate"]},{"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/contentColorEnabled","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/contentColor"],"title":"Card UI Controls - Content"},{"title":"Card UI Controls - Clipping","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShapeEnabled","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shapeRadius","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shouldClipBottomLeft","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shouldClipBottomRight","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shouldClipTopLeft","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shouldClipTopRight"]},{"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isBorderEnabled","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/borderColor","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/borderWidth"],"title":"Card UI Controls - Border"},{"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShadowEnabled","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shadowColor","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shadowOffset","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shadowOpacity","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shadowRadius"],"title":"Card UI Controls - Shadow"},{"title":"View Hierarchy","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/hasSubview(_:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/addSubview(_:)"]},{"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/intrinsicContentSize"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/awakeFromNib()","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/encode(with:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/layoutSubviews()"]}],"relationshipsSections":[{"type":"conformsTo","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(pl)NSCoding","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(pl)NSObject","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(pl)CALayerDelegate","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/s7CVarArgP","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/s28CustomDebugStringConvertibleP","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/s23CustomStringConvertibleP","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/SQ","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/SH","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/s8SendableP","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(pl)UIAccessibilityIdentification","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(pl)UIAppearance","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(pl)UIAppearanceContainer","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(pl)UIContextMenuInteractionDelegate","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(pl)UICoordinateSpace","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(pl)UIDynamicItem","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(pl)UIFocusEnvironment","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(pl)UIFocusItem","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(pl)UIFocusItemContainer","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(pl)UILargeContentViewerItem","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(pl)UITraitEnvironment","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@IBDesignable","kind":"attribute"},{"kind":"text","text":" "},{"text":"@objc","kind":"attribute"},{"text":"(JoynedButton) ","kind":"text"},{"kind":"attribute","text":"@objcMembers"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JoynedButton"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/joynedmobilesdk\/joynedbutton"]},{"paths":["\/documentation\/joynedmobilesdk\/joynedbutton"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/init(coder:)":{"title":"init(coder:)","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"url":"\/documentation\/joynedmobilesdk\/joynedbutton\/init(coder:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"coder","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/init(coder:)","abstract":[{"type":"text","text":"Creates a control from data in an unarchiver."}],"kind":"symbol","role":"symbol"},"doc://co.joyned.mobile.JoynedMobileSDK/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(pl)UIFocusEnvironment"},"doc://co.joyned.mobile.JoynedMobileSDK/objc(pl)UIFocusItem":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(pl)UIFocusItem","title":"UIKit.UIFocusItem","type":"unresolvable"},"doc://co.joyned.mobile.JoynedMobileSDK/@M@JoynedMobileSDK@objc(cs)_JCardControl":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/@M@JoynedMobileSDK@objc(cs)_JCardControl","title":"_JCardControl","type":"unresolvable"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/shouldClipBottomLeft":{"kind":"symbol","abstract":[{"type":"text","text":"Indicates if the bottom left corner should be cliped or not, used for card UI clipping system."},{"type":"text","text":" "},{"type":"text","text":"Only takes effect if the "},{"type":"reference","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShapeEnabled","isActive":true},{"text":" is set to ","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"url":"\/documentation\/joynedmobilesdk\/joynedbutton\/shouldclipbottomleft","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shouldClipBottomLeft","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shouldClipBottomLeft"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"shouldClipBottomLeft"}],"role":"symbol","type":"topic","title":"shouldClipBottomLeft"},"doc://co.joyned.mobile.JoynedMobileSDK/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer","type":"unresolvable"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/shouldClipBottomRight":{"kind":"symbol","abstract":[{"type":"text","text":"Indicates if the bottom right corner should be cliped or not, used for card UI clipping system."},{"type":"text","text":" "},{"text":"Only takes effect if the ","type":"text"},{"type":"reference","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShapeEnabled","isActive":true},{"type":"text","text":" is set to "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"url":"\/documentation\/joynedmobilesdk\/joynedbutton\/shouldclipbottomright","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shouldClipBottomRight","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"shouldClipBottomRight","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"shouldClipBottomRight"}],"role":"symbol","type":"topic","title":"shouldClipBottomRight"},"doc://co.joyned.mobile.JoynedMobileSDK/SH":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/init(frame:)":{"title":"init(frame:)","navigatorTitle":[{"text":"initWithFrame:","kind":"identifier"}],"url":"\/documentation\/joynedmobilesdk\/joynedbutton\/init(frame:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/init(frame:)","abstract":[{"type":"text","text":"Creates a control with the specified frame."}],"kind":"symbol","role":"symbol"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/isBorderEnabled":{"url":"\/documentation\/joynedmobilesdk\/joynedbutton\/isborderenabled","navigatorTitle":[{"kind":"identifier","text":"isBorderEnabled"}],"kind":"symbol","title":"isBorderEnabled","abstract":[{"type":"text","text":"Determins if the card content should have a border drawn or not, defaults to false"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isBorderEnabled","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isBorderEnabled","role":"symbol"},"doc://co.joyned.mobile.JoynedMobileSDK/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring","type":"unresolvable"},"doc://co.joyned.mobile.JoynedMobileSDK/objc(pl)UIDynamicItem":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(pl)UIDynamicItem","title":"UIKit.UIDynamicItem","type":"unresolvable"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/isShadowEnabled":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isShadowEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"title":"isShadowEnabled","abstract":[{"text":"Determins if the card content should have a shadow outline or not, defaults to false","type":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isShadowEnabled"}],"kind":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShadowEnabled","url":"\/documentation\/joynedmobilesdk\/joynedbutton\/isshadowenabled"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/intrinsicContentSize":{"abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"intrinsicContentSize","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"}],"navigatorTitle":[{"kind":"identifier","text":"intrinsicContentSize"}],"title":"intrinsicContentSize","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/intrinsicContentSize","url":"\/documentation\/joynedmobilesdk\/joynedbutton\/intrinsiccontentsize","type":"topic","role":"symbol","kind":"symbol"},"doc://co.joyned.mobile.JoynedMobileSDK/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(pl)NSCoding"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/shouldClipTopRight":{"url":"\/documentation\/joynedmobilesdk\/joynedbutton\/shouldcliptopright","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"shouldClipTopRight"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldClipTopRight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[{"type":"text","text":"Indicates if the top right corner should be cliped or not, used for card UI clipping system."},{"type":"text","text":" "},{"type":"text","text":"Only takes effect if the "},{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShapeEnabled","type":"reference","isActive":true},{"text":" is set to ","type":"text"},{"code":"true","type":"codeVoice"},{"type":"text","text":"."}],"title":"shouldClipTopRight","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shouldClipTopRight"},"doc://co.joyned.mobile.JoynedMobileSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/s23CustomStringConvertibleP"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/borderColor":{"url":"\/documentation\/joynedmobilesdk\/joynedbutton\/bordercolor","navigatorTitle":[{"kind":"identifier","text":"borderColor"}],"kind":"symbol","title":"borderColor","abstract":[{"type":"text","text":"Controls the border’s color paramater, only takes effect if the "},{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isBorderEnabled","type":"reference","isActive":true},{"text":" is set to ","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"Transperent by default.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"borderColor","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/borderColor","role":"symbol"},"doc://co.joyned.mobile.JoynedMobileSDK/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://co.joyned.mobile.JoynedMobileSDK/objc(pl)NSObject":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://co.joyned.mobile.JoynedMobileSDK/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/contentColor":{"title":"contentColor","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/contentColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"contentColor"},{"kind":"text","text":": "},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"text":"contentColor","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The color to be used for card UI background color, only takes effect if the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/contentColorEnabled"},{"type":"text","text":" is set to "},{"code":"true","type":"codeVoice"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Transperent by default."}],"url":"\/documentation\/joynedmobilesdk\/joynedbutton\/contentcolor","role":"symbol"},"doc://co.joyned.mobile.JoynedMobileSDK/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(pl)UITraitEnvironment"},"doc://co.joyned.mobile.JoynedMobileSDK/objc(pl)UIFocusItemContainer":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(pl)UIFocusItemContainer","title":"UIKit.UIFocusItemContainer","type":"unresolvable"},"doc://co.joyned.mobile.JoynedMobileSDK/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/hasSubview(_:)":{"role":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/hasSubview(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hasSubview"},{"kind":"text","text":"("},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"title":"hasSubview(_:)","url":"\/documentation\/joynedmobilesdk\/joynedbutton\/hassubview(_:)","abstract":[{"text":"Returns true if the passed view is a subview of the reciver","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"hasSubview:","kind":"identifier"}],"type":"topic"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/shadowOpacity":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shadowOpacity"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}],"title":"shadowOpacity","abstract":[{"type":"text","text":"The opacity level of the shadow used by the card UI, only takes effect if the "},{"type":"reference","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShadowEnabled","isActive":true},{"type":"text","text":" is set to "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."},{"text":" ","type":"text"},{"text":"Zero by default.","type":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"shadowOpacity","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shadowOpacity","url":"\/documentation\/joynedmobilesdk\/joynedbutton\/shadowopacity"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/isShapeEnabled":{"kind":"symbol","abstract":[{"type":"text","text":"Determins if the card content should its corners cliped or not, defaults to false"}],"url":"\/documentation\/joynedmobilesdk\/joynedbutton\/isshapeenabled","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShapeEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isShapeEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"isShapeEnabled"}],"role":"symbol","type":"topic","title":"isShapeEnabled"},"doc://co.joyned.mobile.JoynedMobileSDK/objc(pl)CALayerDelegate":{"title":"QuartzCore.CALayerDelegate","type":"unresolvable","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(pl)CALayerDelegate"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/shadowColor":{"navigatorTitle":[{"text":"shadowColor","kind":"identifier"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shadowColor","url":"\/documentation\/joynedmobilesdk\/joynedbutton\/shadowcolor","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"shadowColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"title":"shadowColor","abstract":[{"text":"The color to be used for card UI shadow color, only takes effect if the ","type":"text"},{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShadowEnabled","isActive":true,"type":"reference"},{"type":"text","text":" is set to "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Transperent by default."}],"kind":"symbol","role":"symbol","type":"topic"},"doc://co.joyned.mobile.JoynedMobileSDK/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable","type":"unresolvable"},"doc://co.joyned.mobile.JoynedMobileSDK/objc(pl)UIAppearance":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(pl)UIAppearance","title":"UIKit.UIAppearance","type":"unresolvable"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/encode(with:)":{"abstract":[{"type":"text","text":"Encodes the receiver using a given archiver."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"encode","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder"},{"text":")","kind":"text"}],"url":"\/documentation\/joynedmobilesdk\/joynedbutton\/encode(with:)","role":"symbol","title":"encode(with:)","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/encode(with:)","navigatorTitle":[{"kind":"identifier","text":"encodeWithCoder:"}],"kind":"symbol","type":"topic"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/hosted_ui":{"url":"\/documentation\/joynedmobilesdk\/hosted_ui","kind":"article","type":"topic","abstract":[{"type":"text","text":"Hosted Joyned UI"},{"text":" ","type":"text"},{"text":"Joyned mobile SDK provides a few views which are ment to be used within application that hosts the SDK","type":"text"}],"title":"Hosted UI","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/hosted_ui","role":"article"},"doc://co.joyned.mobile.JoynedMobileSDK/objc(pl)UICoordinateSpace":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(pl)UICoordinateSpace","title":"UIKit.UICoordinateSpace","type":"unresolvable"},"doc://co.joyned.mobile.JoynedMobileSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/SQ"},"doc://co.joyned.mobile.JoynedMobileSDK/objc(pl)UILargeContentViewerItem":{"title":"UIKit.UILargeContentViewerItem","type":"unresolvable","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(pl)UILargeContentViewerItem"},"doc://co.joyned.mobile.JoynedMobileSDK/objc(pl)UIAccessibilityIdentification":{"title":"UIKit.UIAccessibilityIdentification","type":"unresolvable","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(pl)UIAccessibilityIdentification"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButtonDelegate":{"abstract":[],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate","url":"\/documentation\/joynedmobilesdk\/joynedbuttondelegate","type":"topic","title":"JoynedButtonDelegate","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JoynedButtonDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"JoynedButtonDelegate"}]},"doc://co.joyned.mobile.JoynedMobileSDK/objc(pl)UIContextMenuInteractionDelegate":{"title":"UIKit.UIContextMenuInteractionDelegate","type":"unresolvable","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(pl)UIContextMenuInteractionDelegate"},"doc://co.joyned.mobile.JoynedMobileSDK/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","type":"unresolvable","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(pl)UIResponderStandardEditActions"},"doc://co.joyned.mobile.JoynedMobileSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/s7CVarArgP"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/GettingStarted":{"title":"Getting Started with Joyned mobile SDK","url":"\/documentation\/gettingstarted","type":"topic","abstract":[],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/GettingStarted","kind":"article","role":"collection"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/shapeRadius":{"kind":"symbol","abstract":[{"type":"text","text":"The corner clipping radius, used for card UI clipping system. Only takes effect if the "},{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShapeEnabled","isActive":true,"type":"reference"},{"text":" is set to ","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"url":"\/documentation\/joynedmobilesdk\/joynedbutton\/shaperadius","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shapeRadius","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shapeRadius"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"}],"navigatorTitle":[{"kind":"identifier","text":"shapeRadius"}],"role":"symbol","type":"topic","title":"shapeRadius"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/layoutSubviews()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"},{"text":"()","kind":"text"}],"title":"layoutSubviews()","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/layoutSubviews()","kind":"symbol","type":"topic","abstract":[{"text":"Lays out subviews.","type":"text"}],"url":"\/documentation\/joynedmobilesdk\/joynedbutton\/layoutsubviews()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/borderWidth":{"url":"\/documentation\/joynedmobilesdk\/joynedbutton\/borderwidth","navigatorTitle":[{"kind":"identifier","text":"borderWidth"}],"kind":"symbol","title":"borderWidth","abstract":[{"type":"text","text":"Controls the border’s width paramater, only takes effect if the "},{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isBorderEnabled","type":"reference","isActive":true},{"type":"text","text":" is set to "},{"code":"true","type":"codeVoice"},{"type":"text","text":"."}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"borderWidth"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/borderWidth","role":"symbol"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/delegate":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": "},{"text":"JoynedButtonDelegate","preciseIdentifier":"c:@M@JoynedMobileSDK@objc(pl)JoynedButtonDelegate","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"kind":"symbol","title":"delegate","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/delegate","abstract":[],"url":"\/documentation\/joynedmobilesdk\/joynedbutton\/delegate","type":"topic"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"JoynedButton","kind":"identifier"}],"title":"JoynedButton","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton","kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/joynedmobilesdk\/joynedbutton","role":"symbol","navigatorTitle":[{"text":"JoynedButton","kind":"identifier"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/shadowOffset":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shadowOffset"},{"kind":"text","text":": "},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"}],"title":"shadowOffset","abstract":[{"type":"text","text":"The offset  of the shadow used by the card UI, only takes effect if the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShadowEnabled"},{"type":"text","text":" is set to "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."},{"text":" ","type":"text"},{"text":"Zero by default.","type":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"shadowOffset","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shadowOffset","url":"\/documentation\/joynedmobilesdk\/joynedbutton\/shadowoffset"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/contentColorEnabled":{"title":"contentColorEnabled","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/contentColorEnabled","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"contentColorEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"contentColorEnabled"}],"type":"topic","abstract":[{"type":"text","text":"Determins if the card content should have a background color, defaults to false"}],"url":"\/documentation\/joynedmobilesdk\/joynedbutton\/contentcolorenabled","role":"symbol"},"doc://co.joyned.mobile.JoynedMobileSDK/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/s8SendableP","title":"Swift.Sendable"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/shouldClipTopLeft":{"url":"\/documentation\/joynedmobilesdk\/joynedbutton\/shouldcliptopleft","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"shouldClipTopLeft"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldClipTopLeft"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Indicates if the top left corner should be cliped or not, used for card UI clipping system."},{"text":" ","type":"text"},{"text":"Only takes effect if the ","type":"text"},{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShapeEnabled","type":"reference","isActive":true},{"type":"text","text":" is set to "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"title":"shouldClipTopLeft","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shouldClipTopLeft"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/addSubview(_:)":{"role":"symbol","navigatorTitle":[{"text":"addSubview:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"addSubview","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":")"}],"kind":"symbol","title":"addSubview(_:)","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/addSubview(_:)","abstract":[{"type":"text","text":"Adds a view to the end of the receiver’s list of subviews."}],"url":"\/documentation\/joynedmobilesdk\/joynedbutton\/addsubview(_:)","type":"topic"},"doc://co.joyned.mobile.JoynedMobileSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/shadowRadius":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shadowRadius"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"title":"shadowRadius","abstract":[{"text":"The radius of the shadow used by the card UI, only takes effect if the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShadowEnabled","type":"reference"},{"text":" is set to ","type":"text"},{"code":"true","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"Zero by default.","type":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"shadowRadius"}],"kind":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shadowRadius","url":"\/documentation\/joynedmobilesdk\/joynedbutton\/shadowradius"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/awakeFromNib()":{"navigatorTitle":[{"kind":"identifier","text":"awakeFromNib"}],"abstract":[{"type":"text","text":"Prepares the receiver for service after it has been loaded from an Interface Builder archive, or nib file."}],"type":"topic","url":"\/documentation\/joynedmobilesdk\/joynedbutton\/awakefromnib()","kind":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/awakeFromNib()","title":"awakeFromNib()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"awakeFromNib","kind":"identifier"},{"kind":"text","text":"()"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","value":"JoynedButton","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"JoynedButton"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"JoynedButton","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Creating a Joyned Button","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/init(frame:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/init(coder:)"]},{"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/delegate","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate"],"title":"Delegations"},{"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/contentColorEnabled","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/contentColor"],"title":"Card UI Controls - Content"},{"title":"Card UI Controls - Clipping","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShapeEnabled","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shapeRadius","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shouldClipBottomLeft","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shouldClipBottomRight","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shouldClipTopLeft","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shouldClipTopRight"]},{"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isBorderEnabled","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/borderColor","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/borderWidth"],"title":"Card UI Controls - Border"},{"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShadowEnabled","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shadowColor","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shadowOffset","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shadowOpacity","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shadowRadius"],"title":"Card UI Controls - Shadow"},{"title":"View Hierarchy","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/hasSubview(_:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/addSubview(_:)"]},{"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/intrinsicContentSize"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/awakeFromNib()","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/encode(with:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/layoutSubviews()"]}],"path":"\/topicSections"},{"value":[{"type":"inheritsFrom","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/@M@JoynedMobileSDK@objc(cs)_JCardControl"],"kind":"relationships","title":"Inherits From"}],"path":"\/relationshipsSections","op":"replace"},{"op":"replace","path":"\/seeAlsoSections","value":[{"generated":true,"title":"Hosted Joyned UI","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate"]}]},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JoynedButton"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JoynedMobileSDK@objc(cs)_JCardControl","text":"_JCardControl"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"initWithCoder:","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1init(coder:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1init(coder:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shouldClipBottomLeft\/title","value":"shouldClipBottomLeft"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shouldClipBottomLeft\/fragments","value":[{"text":"shouldClipBottomLeft","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shouldClipBottomRight\/title","value":"shouldClipBottomRight"},{"op":"replace","value":[{"text":"shouldClipBottomRight","kind":"identifier"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shouldClipBottomRight\/fragments"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1init(frame:)\/title","value":"initWithFrame:","op":"replace"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1init(frame:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}],"op":"replace"},{"op":"replace","value":"isBorderEnabled","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1isBorderEnabled\/title"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1isBorderEnabled\/fragments","op":"replace","value":[{"kind":"identifier","text":"isBorderEnabled"}]},{"op":"replace","value":"isShadowEnabled","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1isShadowEnabled\/title"},{"op":"replace","value":[{"text":"isShadowEnabled","kind":"identifier"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1isShadowEnabled\/fragments"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1intrinsicContentSize\/title","value":"intrinsicContentSize","op":"replace"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1intrinsicContentSize\/fragments","op":"replace","value":[{"text":"intrinsicContentSize","kind":"identifier"}]},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shouldClipTopRight\/title","value":"shouldClipTopRight","op":"replace"},{"value":[{"kind":"identifier","text":"shouldClipTopRight"}],"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shouldClipTopRight\/fragments"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1borderColor\/title","value":"borderColor","op":"replace"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1borderColor\/fragments","value":[{"kind":"identifier","text":"borderColor"}],"op":"replace"},{"value":"contentColor","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1contentColor\/title"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1contentColor\/fragments","value":[{"kind":"identifier","text":"contentColor"}],"op":"replace"},{"value":"hasSubview:","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1hasSubview(_:)\/title"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1hasSubview(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"hasSubview:"}],"op":"replace"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shadowOpacity\/title","op":"replace","value":"shadowOpacity"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shadowOpacity\/fragments","op":"replace","value":[{"kind":"identifier","text":"shadowOpacity"}]},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1isShapeEnabled\/title","value":"isShapeEnabled","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1isShapeEnabled\/fragments","value":[{"text":"isShapeEnabled","kind":"identifier"}]},{"value":"shadowColor","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shadowColor\/title"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shadowColor\/fragments","value":[{"kind":"identifier","text":"shadowColor"}]},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1encode(with:)\/title","value":"encodeWithCoder:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"encodeWithCoder:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1encode(with:)\/fragments"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButtonDelegate\/title","op":"replace","value":"JoynedButtonDelegate"},{"value":[{"text":"JoynedButtonDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButtonDelegate\/fragments"},{"op":"replace","value":"shapeRadius","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shapeRadius\/title"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shapeRadius\/fragments","value":[{"text":"shapeRadius","kind":"identifier"}],"op":"replace"},{"value":"layoutSubviews","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1layoutSubviews()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}],"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1layoutSubviews()\/fragments"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1borderWidth\/title","value":"borderWidth","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"borderWidth"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1borderWidth\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1delegate\/title","value":"delegate"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1delegate\/fragments","op":"replace","value":[{"text":"delegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton\/title","op":"replace","value":"JoynedButton"},{"value":[{"text":"JoynedButton","kind":"identifier"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton\/fragments","op":"replace"},{"value":"shadowOffset","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shadowOffset\/title"},{"value":[{"text":"shadowOffset","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shadowOffset\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1contentColorEnabled\/title","value":"contentColorEnabled"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1contentColorEnabled\/fragments","value":[{"text":"contentColorEnabled","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shouldClipTopLeft\/title","value":"shouldClipTopLeft"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shouldClipTopLeft\/fragments","value":[{"text":"shouldClipTopLeft","kind":"identifier"}]},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1addSubview(_:)\/title","op":"replace","value":"addSubview:"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1addSubview(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"addSubview:","kind":"identifier"}]},{"value":"shadowRadius","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shadowRadius\/title"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shadowRadius\/fragments","op":"replace","value":[{"text":"shadowRadius","kind":"identifier"}]},{"value":"awakeFromNib","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1awakeFromNib()\/title"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1awakeFromNib()\/fragments","value":[{"kind":"text","text":"- "},{"text":"awakeFromNib","kind":"identifier"}],"op":"replace"}]}]}