{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedTransactionRequest"},"kind":"symbol","metadata":{"roleHeading":"Class","modules":[{"name":"JoynedMobileSDK"}],"role":"symbol","navigatorTitle":[{"text":"JoynedTransactionRequest","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"JoynedTransactionRequest","kind":"identifier"}],"symbolKind":"class","externalID":"c:@M@JoynedMobileSDK@objc(cs)JoynedTransactionRequest","title":"JoynedTransactionRequest"},"topicSections":[{"title":"Creating a transaction request","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedTransactionRequest\/init(transaction:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedTransactionRequest\/init(transactionDictionary:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedTransactionRequest\/init(transactionString:)"]},{"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedTransactionRequest\/transaction","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedTransactionRequest\/transactionJSON"],"title":"Accessing request payload"}],"seeAlsoSections":[{"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/transaction"],"generated":true,"title":"Transaction report API"}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"type":"conformsTo","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(pl)NSObject","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/s7CVarArgP","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/s28CustomDebugStringConvertibleP","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/s23CustomStringConvertibleP","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/SQ","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/SH"],"title":"Conforms To","kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/GettingStarted"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(JoynedTransactionRequest) "},{"kind":"attribute","text":"@objcMembers"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JoynedTransactionRequest"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/joynedmobilesdk\/joynedtransactionrequest"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/joynedmobilesdk\/joynedtransactionrequest"]}],"references":{"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedTransactionRequest/init(transactionString:)":{"kind":"symbol","type":"topic","title":"init(transactionString:)","navigatorTitle":[{"kind":"identifier","text":"initWithTransactionString:"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedTransactionRequest\/init(transactionString:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"transactionString"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"url":"\/documentation\/joynedmobilesdk\/joynedtransactionrequest\/init(transactionstring:)","role":"symbol","abstract":[{"text":"Returns a Transaction Request object with imutable payload","type":"text"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedTransactionRequest":{"kind":"symbol","type":"topic","title":"JoynedTransactionRequest","navigatorTitle":[{"kind":"identifier","text":"JoynedTransactionRequest"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedTransactionRequest","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JoynedTransactionRequest"}],"url":"\/documentation\/joynedmobilesdk\/joynedtransactionrequest","role":"symbol","abstract":[]},"doc://co.joyned.mobile.JoynedMobileSDK/objc(pl)NSObject":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://co.joyned.mobile.JoynedMobileSDK/s7CVarArgP":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://co.joyned.mobile.JoynedMobileSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://co.joyned.mobile.JoynedMobileSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://co.joyned.mobile.JoynedMobileSDK/objc(cs)NSObject":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/transaction":{"url":"\/documentation\/joynedmobilesdk\/transaction","title":"Report transaction","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/transaction","kind":"article","type":"topic","role":"article","abstract":[{"text":"API to make joyned is aware of all purchase transactions processed by your application.","type":"text"}]},"doc://co.joyned.mobile.JoynedMobileSDK/SQ":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/GettingStarted":{"kind":"article","role":"collection","url":"\/documentation\/gettingstarted","type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/GettingStarted","title":"Getting Started with Joyned mobile SDK","abstract":[]},"doc://co.joyned.mobile.JoynedMobileSDK/SH":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedTransactionRequest/transaction":{"navigatorTitle":[{"kind":"identifier","text":"transaction"}],"type":"topic","abstract":[{"text":"A dictionary of transaction data stores the information extracted by the system when the request was initialized","type":"text"}],"kind":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedTransactionRequest\/transaction","title":"transaction","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transaction","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSDictionary","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary"}],"url":"\/documentation\/joynedmobilesdk\/joynedtransactionrequest\/transaction"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedTransactionRequest/init(transactionDictionary:)":{"kind":"symbol","type":"topic","title":"init(transactionDictionary:)","navigatorTitle":[{"kind":"identifier","text":"initWithTransactionDictionary:"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedTransactionRequest\/init(transactionDictionary:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"transactionDictionary","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary"},{"kind":"text","text":")"}],"url":"\/documentation\/joynedmobilesdk\/joynedtransactionrequest\/init(transactiondictionary:)","role":"symbol","abstract":[{"type":"text","text":"Returns a Transaction Request object with imutable payload"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedTransactionRequest/transactionJSON":{"navigatorTitle":[{"kind":"identifier","text":"transactionJSON"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedTransactionRequest\/transactionJSON","abstract":[{"text":"A JSON string representation of the transaction request payload","type":"text"}],"title":"transactionJSON","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transactionJSON","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/joynedmobilesdk\/joynedtransactionrequest\/transactionjson"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedTransactionRequest/init(transaction:)":{"kind":"symbol","type":"topic","title":"init(transaction:)","navigatorTitle":[{"text":"initWithTransaction:","kind":"identifier"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedTransactionRequest\/init(transaction:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"transaction"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"url":"\/documentation\/joynedmobilesdk\/joynedtransactionrequest\/init(transaction:)","role":"symbol","abstract":[{"type":"text","text":"Returns a Transaction Request object with imutable payload"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","value":"JoynedTransactionRequest","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"text":"JoynedTransactionRequest","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"JoynedTransactionRequest","kind":"identifier"}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedTransactionRequest\/init(transaction:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedTransactionRequest\/init(transactionDictionary:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedTransactionRequest\/init(transactionString:)"],"title":"Creating a transaction request"},{"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedTransactionRequest\/transaction","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedTransactionRequest\/transactionJSON"],"title":"Accessing request payload"}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"}]},{"op":"replace","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JoynedTransactionRequest"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"initWithTransactionString:","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedTransactionRequest~1init(transactionString:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedTransactionRequest~1init(transactionString:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithTransactionString:","kind":"identifier"}]},{"value":"JoynedTransactionRequest","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedTransactionRequest\/title"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedTransactionRequest\/fragments","value":[{"text":"JoynedTransactionRequest","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedTransactionRequest~1transaction\/title","op":"replace","value":"transaction"},{"op":"replace","value":[{"text":"transaction","kind":"identifier"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedTransactionRequest~1transaction\/fragments"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedTransactionRequest~1init(transactionDictionary:)\/title","op":"replace","value":"initWithTransactionDictionary:"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedTransactionRequest~1init(transactionDictionary:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithTransactionDictionary:"}],"op":"replace"},{"value":"transactionJSON","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedTransactionRequest~1transactionJSON\/title"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedTransactionRequest~1transactionJSON\/fragments","op":"replace","value":[{"text":"transactionJSON","kind":"identifier"}]},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedTransactionRequest~1init(transaction:)\/title","op":"replace","value":"initWithTransaction:"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithTransaction:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedTransactionRequest~1init(transaction:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}