{"identifier":{"url":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/screen_llst","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Joyned Mobile SDK screen change monitor"}],"primaryContentSections":[{"content":[{"level":2,"anchor":"Overview","type":"heading","text":"Overview"},{"inlineContent":[{"type":"text","text":"Joyned Mobile SDK monitors the host application for screen changes and adjusts its display accordingly."}],"type":"paragraph"},{"inlineContent":[{"text":"The system has several ways to effect when Joyend content is showing or not.","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"Screen List"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Auto - plist based black \/ white list"}]}]},{"content":[{"inlineContent":[{"text":"Manual - black \/ white list update in code","type":"text"}],"type":"paragraph"}]}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Manual screen controls"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Hide \/ Show display"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Minimize display"}],"type":"paragraph"}]}]}]}],"type":"unorderedList"},{"type":"heading","level":3,"anchor":"Screen-List-Validation-Controls","text":"Screen List Validation Controls"},{"tabs":[{"content":[{"inlineContent":[{"text":"Add JoynedMobileSDKScreenlists as a Dictionary to the ","type":"text"},{"type":"strong","inlineContent":[{"text":"Joyned-Info","type":"text"}]},{"type":"text","text":" plist file to configure automatic screenlist."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"To the resulting Dictionary add the following keys with the relevant string arrays:"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"JoynedMobileSDKScreenWhitelist"}]}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"JoynedMobileSDKScreenBlacklist"}]}],"type":"paragraph"}]}],"type":"unorderedList"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Note: Entries in the blacklist take president over the ones in whitelist"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Example:"}]},{"type":"codeListing","syntax":"xml","code":["<key>JoynedMobileSDKScreenlists<\/key>","<dict>","    <key>JoynedMobileSDKScreenWhitelist<\/key>","    <array>","        <string>DealsFeedViewController<\/string>","        <string>ProductViewController<\/string>","        <string>StatusViewController<\/string>","        <string>SavedViewController<\/string>","        <string>ProfileViewController<\/string>","    <\/array>","    <key>JoynedMobileSDKScreenBlacklist<\/key>","    <array>","        <string>SplashViewController<\/string>","        <string>PurchaseViewController<\/string>","        <string>UIViewController<\/string>","        <string>ProfileViewController<\/string>","    <\/array>","<\/dict>"]}],"title":"Automatic"},{"content":[{"type":"paragraph","inlineContent":[{"text":"You can add or remove additional screen from the system black\/white list with the following API via the public access point (","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK"},{"text":")","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/append(WhiteList:)","isActive":true}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/remove(WhiteList:)","isActive":true}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/append(BlackList:)"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/remove(BlackList:)","type":"reference","isActive":true}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/clearScreensBlackList()","type":"reference"}]}]}]}],"title":"Manual"}],"type":"tabNavigator"},{"level":3,"type":"heading","text":"Manual screen controls","anchor":"Manual-screen-controls"},{"inlineContent":[{"type":"text","text":"You can use the JoynedMobileSDK via its public access point ("},{"isActive":true,"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK","type":"reference"},{"type":"text","text":") to effect how the Joyned UI acts."}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/hideDisplay()","type":"reference"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/showDisplay()","isActive":true,"type":"reference"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/minimizeDisplay()"}]}]}],"type":"unorderedList"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/GettingStarted"],["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/GettingStarted","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK"]]},"kind":"article","sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"roleHeading":"Article","role":"article","modules":[{"name":"JoynedMobileSDK"}],"title":"Screen Validation Controls"},"seeAlsoSections":[{"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/installation","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/activation","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/global_delegate","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate"],"generated":true,"title":"Essentials"}],"references":{"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK/showDisplay()":{"url":"\/documentation\/joynedmobilesdk\/joynedsdk\/showdisplay()","abstract":[{"text":"Use this method to make the system show the floating SDK UI elements, if they have been hidden before","type":"text"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/showDisplay()","role":"symbol","kind":"symbol","title":"showDisplay()","type":"topic","navigatorTitle":[{"text":"showDisplay","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showDisplay","kind":"identifier"},{"kind":"text","text":"()"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK/append(WhiteList:)":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/append(WhiteList:)","type":"topic","kind":"symbol","title":"append(WhiteList:)","role":"symbol","navigatorTitle":[{"text":"appendWithWhiteList:","kind":"identifier"}],"abstract":[{"type":"text","text":"Use this method to add a new screen name to the system white list"},{"type":"text","text":" "},{"text":"On screens which appear in the whitelist the Joyned mobile SDK will present it’s floating content,","type":"text"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdk\/append(whitelist:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"append"},{"kind":"text","text":"("},{"text":"WhiteList","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK/append(BlackList:)":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/append(BlackList:)","kind":"symbol","type":"topic","title":"append(BlackList:)","role":"symbol","navigatorTitle":[{"text":"appendWithBlackList:","kind":"identifier"}],"abstract":[{"type":"text","text":"Use this method to add a new screen name to the system black list"},{"type":"text","text":" "},{"text":"On screens which appear in the blacklist the Joyned mobile SDK will not present it’s floating content,","type":"text"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdk\/append(blacklist:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"append"},{"kind":"text","text":"("},{"kind":"externalParam","text":"BlackList"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/activation":{"url":"\/documentation\/joynedmobilesdk\/activation","title":"Activation Methods","kind":"article","role":"article","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/activation","abstract":[{"type":"text","text":"There are several different ways to activate of the Joyned mobile SDK"}],"type":"topic"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/GettingStarted":{"kind":"article","role":"collection","url":"\/documentation\/gettingstarted","type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/GettingStarted","title":"Getting Started with Joyned mobile SDK","abstract":[]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK/remove(WhiteList:)":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/remove(WhiteList:)","type":"topic","kind":"symbol","title":"remove(WhiteList:)","role":"symbol","navigatorTitle":[{"text":"removeWithWhiteList:","kind":"identifier"}],"abstract":[{"type":"text","text":"Use this method to remove a screen name to the system white list"},{"type":"text","text":" "},{"text":"On screens which appear in the whitelist the Joyned mobile SDK will present it’s floating content,","type":"text"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdk\/remove(whitelist:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"remove"},{"kind":"text","text":"("},{"text":"WhiteList","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK/minimizeDisplay()":{"url":"\/documentation\/joynedmobilesdk\/joynedsdk\/minimizedisplay()","abstract":[{"text":"Use this method to trigger a minimize action on the floating SDK UI elements,","type":"text"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/minimizeDisplay()","role":"symbol","kind":"symbol","title":"minimizeDisplay()","type":"topic","navigatorTitle":[{"kind":"identifier","text":"minimizeDisplay"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minimizeDisplay"},{"text":"()","kind":"text"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK/remove(BlackList:)":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/remove(BlackList:)","kind":"symbol","type":"topic","title":"remove(BlackList:)","role":"symbol","navigatorTitle":[{"text":"removeWithBlackList:","kind":"identifier"}],"abstract":[{"type":"text","text":"Use this method to remove a  screen name to the system black list"},{"type":"text","text":" "},{"text":"On screens which appear in the blacklist the Joyned mobile SDK will not present it’s floating content,","type":"text"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdk\/remove(blacklist:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"remove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"BlackList"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDKDelegate":{"title":"JoynedSDKDelegate","url":"\/documentation\/joynedmobilesdk\/joynedsdkdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JoynedSDKDelegate"}],"navigatorTitle":[{"text":"JoynedSDKDelegate","kind":"identifier"}],"abstract":[{"text":"Implement this to recive notifications on major actions taken by the SDK and affect its behavior","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK":{"kind":"symbol","type":"topic","url":"\/documentation\/joynedmobilesdk\/joynedsdk","abstract":[{"text":"The main public access class to ther Joyned mobile SDK, use it to interact with the system","type":"text"}],"title":"JoynedSDK","role":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JoynedSDK"}],"navigatorTitle":[{"text":"JoynedSDK","kind":"identifier"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK/clearScreensBlackList()":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/clearScreensBlackList()","kind":"symbol","type":"topic","title":"clearScreensBlackList()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"clearScreensBlackList"}],"abstract":[{"text":"Use this method to clear the invalid screen names from the system black list","type":"text"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdk\/clearscreensblacklist()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clearScreensBlackList"},{"kind":"text","text":"()"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/installation":{"url":"\/documentation\/joynedmobilesdk\/installation","title":"Library installation","kind":"article","role":"article","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/installation","abstract":[{"type":"text","text":"How to install this library"}],"type":"topic"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/global_delegate":{"url":"\/documentation\/joynedmobilesdk\/global_delegate","title":"Global Delegate","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/global_delegate","kind":"article","type":"topic","role":"article","abstract":[{"text":"Joyned mobile SDK provides several intervention hooks via the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate","type":"reference"},{"text":" protocol","type":"text"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK/hideDisplay()":{"url":"\/documentation\/joynedmobilesdk\/joynedsdk\/hidedisplay()","abstract":[{"text":"Use this method to make the system hide the floating SDK UI elements","type":"text"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/hideDisplay()","role":"symbol","kind":"symbol","title":"hideDisplay()","type":"topic","navigatorTitle":[{"text":"hideDisplay","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hideDisplay","kind":"identifier"},{"text":"()","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"showDisplay","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1showDisplay()\/title"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"showDisplay"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1showDisplay()\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1append(WhiteList:)\/title","value":"appendWithWhiteList:"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1append(WhiteList:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"appendWithWhiteList:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1append(BlackList:)\/title","value":"appendWithBlackList:","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"appendWithBlackList:"}],"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1append(BlackList:)\/fragments"},{"value":"removeWithWhiteList:","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1remove(WhiteList:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1remove(WhiteList:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"removeWithWhiteList:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1minimizeDisplay()\/title","value":"minimizeDisplay"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"minimizeDisplay"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1minimizeDisplay()\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1remove(BlackList:)\/title","value":"removeWithBlackList:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1remove(BlackList:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"removeWithBlackList:"}]},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDKDelegate\/title","op":"replace","value":"JoynedSDKDelegate"},{"value":[{"text":"JoynedSDKDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDKDelegate\/fragments"},{"value":"JoynedSDK","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK\/title"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK\/fragments","value":[{"text":"JoynedSDK","kind":"identifier"}]},{"op":"replace","value":"clearScreensBlackList","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1clearScreensBlackList()\/title"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1clearScreensBlackList()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"clearScreensBlackList","kind":"identifier"}],"op":"replace"},{"value":"hideDisplay","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1hideDisplay()\/title","op":"replace"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1hideDisplay()\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"hideDisplay"}]}]}]}