{"variants":[{"paths":["\/documentation\/joynedmobilesdk\/transaction"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/joynedmobilesdk\/transaction"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"modules":[{"name":"JoynedMobileSDK"}],"roleHeading":"Article","role":"article","title":"Report transaction"},"primaryContentSections":[{"kind":"content","content":[{"level":2,"text":"Overview","type":"heading","anchor":"Overview"},{"type":"paragraph","inlineContent":[{"text":"The Joyned transaction is an “analytics” fire & forget like API","type":"text"}]},{"inlineContent":[{"type":"text","text":"Simply create a "},{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedTransactionRequest","type":"reference","isActive":true},{"type":"text","text":" object and pass it to the JoynedSDK."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"text":"Code Example:","type":"text"}]}]},{"type":"codeListing","syntax":"swift","code":["let transactionPayload: [String: Any] = [","    \"transactionId\": \"321\",","    \"price\": \"1.23\",","    \"currencyCode\": \"USD\",","    \"productIds\": [\"hotel-123\", \"hotel-456\"]","]","","\/\/ Convert the dictionary to Data","if let data = try? JSONSerialization.data(withJSONObject: transactionPayload, options: .prettyPrinted) {","    ","    \/\/ Convert the Data to a UTF-8 string","    if let json = String(data: data, encoding: .utf8) {","        \/\/ let transaction = \"{\\\"transactionId\\\":\\\"123\\\",\\\"price\\\":\\\"1.23\\\",\\\"currencyCode\\\":\\\"USD\\\",\\\"productIds\\\":[\\\"hotel-123\\\",\\\"hotel-456\\\"]}\"","        JoynedSDK.report(Transaction: JoynedTransactionRequest(transactionString: json))","    }","}"]},{"type":"heading","level":4,"text":"For more information see:","anchor":"For-more-information-see"},{"style":"list","items":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedTransactionRequest","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/report(Transaction:)"],"type":"links"}]}],"identifier":{"url":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/transaction","interfaceLanguage":"swift"},"kind":"article","sections":[],"abstract":[{"text":"API to make joyned is aware of all purchase transactions processed by your application.","type":"text"}],"seeAlsoSections":[{"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedTransactionRequest"],"generated":true,"title":"Transaction report API"}],"hierarchy":{"paths":[["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted"],["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK"]]},"references":{"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/GettingStarted":{"url":"\/documentation\/joynedmobilesdk\/gettingstarted","title":"Getting Started with Joyned mobile SDK","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","type":"topic","abstract":[],"kind":"article","role":"collectionGroup"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK":{"type":"topic","abstract":[{"type":"text","text":"The main public access class to ther Joyned mobile SDK, use it to interact with the system"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JoynedSDK"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK","navigatorTitle":[{"text":"JoynedSDK","kind":"identifier"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdk","kind":"symbol","role":"symbol","title":"JoynedSDK"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK/report(Transaction:)":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/report(Transaction:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"reportWithTransaction:"}],"title":"report(Transaction:)","url":"\/documentation\/joynedmobilesdk\/joynedsdk\/report(transaction:)","abstract":[{"text":"Call this method to report purchase transactions to the Joyned SDK","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"report"},{"kind":"text","text":"("},{"text":"Transaction","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"JoynedTransactionRequest","preciseIdentifier":"c:@M@JoynedMobileSDK@objc(cs)JoynedTransactionRequest"},{"text":"?)","kind":"text"}],"type":"topic"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK":{"url":"\/documentation\/joynedmobilesdk","title":"JoynedMobileSDK","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","type":"topic","abstract":[{"text":"We help people book together. With a better booking experience, better business results","type":"text"}],"kind":"symbol","role":"collection"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedTransactionRequest":{"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JoynedTransactionRequest"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedTransactionRequest","navigatorTitle":[{"kind":"identifier","text":"JoynedTransactionRequest"}],"title":"JoynedTransactionRequest","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedtransactionrequest"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":[{"generated":true,"title":"Transaction report API","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedTransactionRequest"]}],"op":"replace"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK\/title","op":"replace","value":"JoynedSDK"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK\/fragments","value":[{"kind":"identifier","text":"JoynedSDK"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1report(Transaction:)\/title","value":"reportWithTransaction:"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1report(Transaction:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"reportWithTransaction:","kind":"identifier"}]},{"value":"JoynedTransactionRequest","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedTransactionRequest\/title"},{"value":[{"text":"JoynedTransactionRequest","kind":"identifier"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedTransactionRequest\/fragments","op":"replace"}]}]}