{"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"awakeFromNib","kind":"identifier"},{"kind":"text","text":"()"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/GettingStarted","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton"]]},"variants":[{"paths":["\/documentation\/joynedmobilesdk\/joynedbutton\/awakefromnib()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/joynedmobilesdk\/joynedbutton\/awakefromnib()"]}],"kind":"symbol","identifier":{"url":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/awakeFromNib()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Prepares the receiver for service after it has been loaded from an Interface Builder archive, or nib file."}],"metadata":{"modules":[{"name":"JoynedMobileSDK"}],"externalID":"c:@M@JoynedMobileSDK@objc(cs)JoynedButton(im)awakeFromNib","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"awakeFromNib","kind":"identifier"},{"kind":"text","text":"()"}],"title":"awakeFromNib()","roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"text":"awakeFromNib","kind":"identifier"}],"symbolKind":"method"},"references":{"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JoynedButton"}],"role":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedbutton","type":"topic","navigatorTitle":[{"text":"JoynedButton","kind":"identifier"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton","title":"JoynedButton","abstract":[]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/awakeFromNib()":{"abstract":[{"text":"Prepares the receiver for service after it has been loaded from an Interface Builder archive, or nib file.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"awakeFromNib","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","title":"awakeFromNib()","url":"\/documentation\/joynedmobilesdk\/joynedbutton\/awakefromnib()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"awakeFromNib"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/awakeFromNib()"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/GettingStarted":{"kind":"article","role":"collection","url":"\/documentation\/gettingstarted","type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/GettingStarted","title":"Getting Started with Joyned mobile SDK","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"awakeFromNib","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"awakeFromNib","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"awakeFromNib","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton\/title","value":"JoynedButton","op":"replace"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton\/fragments","op":"replace","value":[{"kind":"identifier","text":"JoynedButton"}]},{"value":"awakeFromNib","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1awakeFromNib()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"awakeFromNib","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1awakeFromNib()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}