{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/joynedmobilesdk\/joynedbutton\/contentcolorenabled"]},{"paths":["\/documentation\/joynedmobilesdk\/joynedbutton\/contentcolorenabled"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/GettingStarted","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton"]]},"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@JoynedMobileSDK@objc(cs)JoynedButton(py)contentColorEnabled","role":"symbol","title":"contentColorEnabled","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contentColorEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"modules":[{"name":"JoynedMobileSDK"}],"navigatorTitle":[{"kind":"identifier","text":"contentColorEnabled"}]},"abstract":[{"type":"text","text":"Determins if the card content should have a background color, defaults to false"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/contentColorEnabled"},"kind":"symbol","seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/contentColor"],"title":"Card UI Controls - Content"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@IBInspectable","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"contentColorEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"references":{"doc://co.joyned.mobile.JoynedMobileSDK/documentation/GettingStarted":{"abstract":[],"type":"topic","kind":"article","role":"collection","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/GettingStarted","url":"\/documentation\/gettingstarted","title":"Getting Started with Joyned mobile SDK"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/contentColor":{"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/joynedmobilesdk\/joynedbutton\/contentcolor","navigatorTitle":[{"kind":"identifier","text":"contentColor"}],"abstract":[{"type":"text","text":"The color to be used for card UI background color, only takes effect if the "},{"isActive":true,"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/contentColorEnabled","type":"reference"},{"text":" is set to ","type":"text"},{"type":"codeVoice","code":"true"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Transperent by default."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"contentColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"title":"contentColor","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/contentColor"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/contentColorEnabled":{"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/joynedmobilesdk\/joynedbutton\/contentcolorenabled","navigatorTitle":[{"kind":"identifier","text":"contentColorEnabled"}],"abstract":[{"type":"text","text":"Determins if the card content should have a background color, defaults to false"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contentColorEnabled","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"contentColorEnabled","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/contentColorEnabled"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton":{"abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"JoynedButton"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JoynedButton","kind":"identifier"}],"url":"\/documentation\/joynedmobilesdk\/joynedbutton","title":"JoynedButton"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"contentColorEnabled"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"contentColorEnabled","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/contentColor"],"title":"Card UI Controls - Content","generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentColorEnabled"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"contentColor","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1contentColor\/title"},{"op":"replace","value":[{"text":"contentColor","kind":"identifier"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1contentColor\/fragments"},{"value":"contentColorEnabled","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1contentColorEnabled\/title"},{"op":"replace","value":[{"kind":"identifier","text":"contentColorEnabled"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1contentColorEnabled\/fragments"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton\/title","value":"JoynedButton","op":"replace"},{"value":[{"text":"JoynedButton","kind":"identifier"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton\/fragments","op":"replace"}]}]}