{"seeAlsoSections":[{"title":"Card UI Controls - Shadow","generated":true,"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShadowEnabled","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shadowColor","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shadowOffset","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shadowRadius"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@IBInspectable","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shadowOpacity"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/joynedmobilesdk\/joynedbutton\/shadowopacity"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/joynedmobilesdk\/joynedbutton\/shadowopacity"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@JoynedMobileSDK@objc(cs)JoynedButton(py)shadowOpacity","role":"symbol","navigatorTitle":[{"text":"shadowOpacity","kind":"identifier"}],"symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"JoynedMobileSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shadowOpacity"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}],"title":"shadowOpacity"},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shadowOpacity","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The opacity level of the shadow used by the card UI, only takes effect if the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShadowEnabled"},{"type":"text","text":" is set to "},{"type":"codeVoice","code":"true"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"Zero by default.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/GettingStarted","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton"]]},"references":{"doc://co.joyned.mobile.JoynedMobileSDK/documentation/GettingStarted":{"title":"Getting Started with Joyned mobile SDK","url":"\/documentation\/gettingstarted","type":"topic","abstract":[],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/GettingStarted","kind":"article","role":"collection"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/shadowOffset":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shadowOffset"},{"kind":"text","text":": "},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"}],"title":"shadowOffset","abstract":[{"type":"text","text":"The offset  of the shadow used by the card UI, only takes effect if the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShadowEnabled"},{"type":"text","text":" is set to "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."},{"text":" ","type":"text"},{"text":"Zero by default.","type":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"shadowOffset","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shadowOffset","url":"\/documentation\/joynedmobilesdk\/joynedbutton\/shadowoffset"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/shadowRadius":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shadowRadius"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"title":"shadowRadius","abstract":[{"text":"The radius of the shadow used by the card UI, only takes effect if the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShadowEnabled","type":"reference"},{"text":" is set to ","type":"text"},{"code":"true","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"Zero by default.","type":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"shadowRadius"}],"kind":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shadowRadius","url":"\/documentation\/joynedmobilesdk\/joynedbutton\/shadowradius"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/shadowOpacity":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shadowOpacity"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}],"title":"shadowOpacity","abstract":[{"type":"text","text":"The opacity level of the shadow used by the card UI, only takes effect if the "},{"type":"reference","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShadowEnabled","isActive":true},{"type":"text","text":" is set to "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."},{"text":" ","type":"text"},{"text":"Zero by default.","type":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"shadowOpacity","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shadowOpacity","url":"\/documentation\/joynedmobilesdk\/joynedbutton\/shadowopacity"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"JoynedButton","kind":"identifier"}],"title":"JoynedButton","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton","kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/joynedmobilesdk\/joynedbutton","role":"symbol","navigatorTitle":[{"text":"JoynedButton","kind":"identifier"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/shadowColor":{"navigatorTitle":[{"text":"shadowColor","kind":"identifier"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shadowColor","url":"\/documentation\/joynedmobilesdk\/joynedbutton\/shadowcolor","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"shadowColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"title":"shadowColor","abstract":[{"text":"The color to be used for card UI shadow color, only takes effect if the ","type":"text"},{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShadowEnabled","isActive":true,"type":"reference"},{"type":"text","text":" is set to "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Transperent by default."}],"kind":"symbol","role":"symbol","type":"topic"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/isShadowEnabled":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isShadowEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"title":"isShadowEnabled","abstract":[{"text":"Determins if the card content should have a shadow outline or not, defaults to false","type":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isShadowEnabled"}],"kind":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShadowEnabled","url":"\/documentation\/joynedmobilesdk\/joynedbutton\/isshadowenabled"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"shadowOpacity","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"shadowOpacity"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"replace","path":"\/seeAlsoSections","value":[{"generated":true,"title":"Card UI Controls - Shadow","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShadowEnabled","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shadowColor","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shadowOffset","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shadowRadius"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:f","text":"float"},{"text":" ","kind":"text"},{"text":"shadowOpacity","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"value":"shadowOffset","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shadowOffset\/title"},{"value":[{"kind":"identifier","text":"shadowOffset"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shadowOffset\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shadowRadius\/title","value":"shadowRadius"},{"value":[{"kind":"identifier","text":"shadowRadius"}],"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shadowRadius\/fragments"},{"value":"shadowOpacity","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shadowOpacity\/title"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shadowOpacity\/fragments","value":[{"kind":"identifier","text":"shadowOpacity"}],"op":"replace"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton\/title","op":"replace","value":"JoynedButton"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton\/fragments","op":"replace","value":[{"text":"JoynedButton","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shadowColor\/title","value":"shadowColor"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shadowColor\/fragments","value":[{"text":"shadowColor","kind":"identifier"}]},{"op":"replace","value":"isShadowEnabled","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1isShadowEnabled\/title"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1isShadowEnabled\/fragments","value":[{"kind":"identifier","text":"isShadowEnabled"}]}]}]}