{"identifier":{"url":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shouldClipBottomLeft","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"shouldClipBottomLeft","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"shouldClipBottomLeft","externalID":"c:@M@JoynedMobileSDK@objc(cs)JoynedButton(py)shouldClipBottomLeft","symbolKind":"property","modules":[{"name":"JoynedMobileSDK"}],"roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"text":"shouldClipBottomLeft","kind":"identifier"}]},"seeAlsoSections":[{"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShapeEnabled","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shapeRadius","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shouldClipBottomRight","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shouldClipTopLeft","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shouldClipTopRight"],"title":"Card UI Controls - Clipping","generated":true}],"hierarchy":{"paths":[["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/GettingStarted","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@IBInspectable","kind":"attribute"},{"text":" ","kind":"text"},{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shouldClipBottomLeft"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/joynedmobilesdk\/joynedbutton\/shouldclipbottomleft"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/joynedmobilesdk\/joynedbutton\/shouldclipbottomleft"]}],"abstract":[{"type":"text","text":"Indicates if the bottom left corner should be cliped or not, used for card UI clipping system."},{"type":"text","text":" "},{"type":"text","text":"Only takes effect if the "},{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShapeEnabled","isActive":true,"type":"reference"},{"text":" is set to ","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"sections":[],"references":{"doc://co.joyned.mobile.JoynedMobileSDK/documentation/GettingStarted":{"title":"Getting Started with Joyned mobile SDK","url":"\/documentation\/gettingstarted","type":"topic","abstract":[],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/GettingStarted","kind":"article","role":"collection"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/shouldClipBottomLeft":{"kind":"symbol","abstract":[{"type":"text","text":"Indicates if the bottom left corner should be cliped or not, used for card UI clipping system."},{"type":"text","text":" "},{"type":"text","text":"Only takes effect if the "},{"type":"reference","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShapeEnabled","isActive":true},{"text":" is set to ","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"url":"\/documentation\/joynedmobilesdk\/joynedbutton\/shouldclipbottomleft","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shouldClipBottomLeft","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shouldClipBottomLeft"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"shouldClipBottomLeft"}],"role":"symbol","type":"topic","title":"shouldClipBottomLeft"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/shapeRadius":{"kind":"symbol","abstract":[{"type":"text","text":"The corner clipping radius, used for card UI clipping system. Only takes effect if the "},{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShapeEnabled","isActive":true,"type":"reference"},{"text":" is set to ","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"url":"\/documentation\/joynedmobilesdk\/joynedbutton\/shaperadius","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shapeRadius","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shapeRadius"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"}],"navigatorTitle":[{"kind":"identifier","text":"shapeRadius"}],"role":"symbol","type":"topic","title":"shapeRadius"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"JoynedButton","kind":"identifier"}],"title":"JoynedButton","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton","kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/joynedmobilesdk\/joynedbutton","role":"symbol","navigatorTitle":[{"text":"JoynedButton","kind":"identifier"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/shouldClipTopRight":{"url":"\/documentation\/joynedmobilesdk\/joynedbutton\/shouldcliptopright","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"shouldClipTopRight"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldClipTopRight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[{"type":"text","text":"Indicates if the top right corner should be cliped or not, used for card UI clipping system."},{"type":"text","text":" "},{"type":"text","text":"Only takes effect if the "},{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShapeEnabled","type":"reference","isActive":true},{"text":" is set to ","type":"text"},{"code":"true","type":"codeVoice"},{"type":"text","text":"."}],"title":"shouldClipTopRight","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shouldClipTopRight"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/shouldClipTopLeft":{"url":"\/documentation\/joynedmobilesdk\/joynedbutton\/shouldcliptopleft","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"shouldClipTopLeft"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldClipTopLeft"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Indicates if the top left corner should be cliped or not, used for card UI clipping system."},{"text":" ","type":"text"},{"text":"Only takes effect if the ","type":"text"},{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShapeEnabled","type":"reference","isActive":true},{"type":"text","text":" is set to "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"title":"shouldClipTopLeft","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shouldClipTopLeft"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/isShapeEnabled":{"kind":"symbol","abstract":[{"type":"text","text":"Determins if the card content should its corners cliped or not, defaults to false"}],"url":"\/documentation\/joynedmobilesdk\/joynedbutton\/isshapeenabled","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShapeEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isShapeEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"isShapeEnabled"}],"role":"symbol","type":"topic","title":"isShapeEnabled"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/shouldClipBottomRight":{"kind":"symbol","abstract":[{"type":"text","text":"Indicates if the bottom right corner should be cliped or not, used for card UI clipping system."},{"type":"text","text":" "},{"text":"Only takes effect if the ","type":"text"},{"type":"reference","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShapeEnabled","isActive":true},{"type":"text","text":" is set to "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"url":"\/documentation\/joynedmobilesdk\/joynedbutton\/shouldclipbottomright","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shouldClipBottomRight","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"shouldClipBottomRight","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"shouldClipBottomRight"}],"role":"symbol","type":"topic","title":"shouldClipBottomRight"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"shouldClipBottomLeft","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"shouldClipBottomLeft"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"replace","value":[{"generated":true,"title":"Card UI Controls - Clipping","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShapeEnabled","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shapeRadius","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shouldClipBottomRight","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shouldClipTopLeft","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shouldClipTopRight"]}],"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shouldClipBottomLeft"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":"shouldClipBottomLeft","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shouldClipBottomLeft\/title"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shouldClipBottomLeft\/fragments","op":"replace","value":[{"text":"shouldClipBottomLeft","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shapeRadius\/title","value":"shapeRadius"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shapeRadius\/fragments","op":"replace","value":[{"text":"shapeRadius","kind":"identifier"}]},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton\/title","value":"JoynedButton","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton\/fragments","value":[{"text":"JoynedButton","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shouldClipTopRight\/title","value":"shouldClipTopRight"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shouldClipTopRight\/fragments","value":[{"kind":"identifier","text":"shouldClipTopRight"}]},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shouldClipTopLeft\/title","op":"replace","value":"shouldClipTopLeft"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shouldClipTopLeft\/fragments","value":[{"text":"shouldClipTopLeft","kind":"identifier"}],"op":"replace"},{"value":"isShapeEnabled","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1isShapeEnabled\/title","op":"replace"},{"op":"replace","value":[{"text":"isShapeEnabled","kind":"identifier"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1isShapeEnabled\/fragments"},{"value":"shouldClipBottomRight","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shouldClipBottomRight\/title"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shouldClipBottomRight\/fragments","value":[{"kind":"identifier","text":"shouldClipBottomRight"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}